window.soalKuis = [
  { pertanyaan: "Apa arti dari 'あそびます'?", jawaban: "bermain" },
  { pertanyaan: "Apa arti dari 'およぎます'?", jawaban: "berenang" },
  { pertanyaan: "Apa arti dari 'むかえます'?", jawaban: "menjemput" },
  { pertanyaan: "Apa arti dari 'つかれます'?", jawaban: "lelah" },
  { pertanyaan: "Apa arti dari 'けっこんします'?", jawaban: "menikah" },
  { pertanyaan: "Apa arti dari 'かいものします'?", jawaban: "berbelanja" },
  { pertanyaan: "Apa arti dari 'しょくじします'?", jawaban: "makan (makan bersama / makan di luar)" },
  { pertanyaan: "Apa arti dari 'さんぽします'?", jawaban: "berjalan-jalan" },
  { pertanyaan: "Apa arti dari 'つけます'?", jawaban: "menyalakan" },
  { pertanyaan: "Apa arti dari 'けします'?", jawaban: "mematikan" },
  { pertanyaan: "Apa arti dari 'あけます'?", jawaban: "membuka" },
  { pertanyaan: "Apa arti dari 'しめます'?", jawaban: "menutup" },
  { pertanyaan: "Apa arti dari 'いそぎます'?", jawaban: "bergegas" },
  { pertanyaan: "Apa arti dari 'まちます'?", jawaban: "menunggu" },
  { pertanyaan: "Apa arti dari 'もちます'?", jawaban: "membawa / memegang" },
  { pertanyaan: "Apa arti dari 'とります'?", jawaban: "mengambil" },
  { pertanyaan: "Apa arti dari 'てつだいます'?", jawaban: "membantu" },
  { pertanyaan: "Apa arti dari 'よびます'?", jawaban: "memanggil" },
  { pertanyaan: "Apa arti dari 'はなします'?", jawaban: "berbicara / berbicara dengan" },
  { pertanyaan: "Apa arti dari 'つかいます'?", jawaban: "menggunakan" },
  { pertanyaan: "Apa arti dari 'とめます'?", jawaban: "menghentikan / memarkir" },
  { pertanyaan: "Apa arti dari 'みせます'?", jawaban: "menunjukkan / memperlihatkan" },
  { pertanyaan: "Apa arti dari 'おしえます'?", jawaban: "mengajar / memberitahukan" },
  { pertanyaan: "Apa arti dari 'すわります'?", jawaban: "duduk" },
  { pertanyaan: "Apa arti dari 'たちます'?", jawaban: "berdiri" },
  { pertanyaan: "Apa arti dari 'はいります'?", jawaban: "masuk" },
  { pertanyaan: "Apa arti dari 'でます'?", jawaban: "keluar" },
  { pertanyaan: "Apa arti dari 'ふります'?", jawaban: "turun (hujan/salju)" },
  { pertanyaan: "Apa arti dari 'コピーします'?", jawaban: "menyalin / fotokopi" },
  { pertanyaan: "Apa arti dari 'おきます'?", jawaban: "bangun / bangun tidur" },
  { pertanyaan: "Apa arti dari 'つくります'?", jawaban: "membuat" },
  { pertanyaan: "Apa arti dari 'うります'?", jawaban: "menjual" },
  { pertanyaan: "Apa arti dari 'しります'?", jawaban: "mengetahui" },
  { pertanyaan: "Apa arti dari 'すみます'?", jawaban: "tinggal / menetap" },
  { pertanyaan: "Apa arti dari 'けんきゅうします'?", jawaban: "meneliti" },
  { pertanyaan: "Apa arti dari 'のります'?", jawaban: "naik (kendaraan)" },
  { pertanyaan: "Apa arti dari 'おります'?", jawaban: "turun (kendaraan)" },
  { pertanyaan: "Apa arti dari 'のりかえます'?", jawaban: "ganti (kendaraan / transit)" },
  { pertanyaan: "Apa arti dari 'あびます'?", jawaban: "mandi / menyiram (dengan air, cahaya)" },
  { pertanyaan: "Apa arti dari 'いれます'?", jawaban: "memasukkan" },
  { pertanyaan: "Apa arti dari 'だします'?", jawaban: "mengeluarkan / menyerahkan" },
  { pertanyaan: "Apa arti dari 'おろします'?", jawaban: "menurunkan / menarik (uang)" },
  { pertanyaan: "Apa arti dari 'はいります'?", jawaban: "masuk" },
  { pertanyaan: "Apa arti dari 'でます'?", jawaban: "keluar / lulus" },
  { pertanyaan: "Apa arti dari 'おします'?", jawaban: "menekan / mendorong (tombol dsb.)" },
  { pertanyaan: "Apa arti dari 'のみます'?", jawaban: "minum" },
  { pertanyaan: "Apa arti dari 'はじめます'?", jawaban: "memulai" },
  { pertanyaan: "Apa arti dari 'けんがくします'?", jawaban: "mengunjungi untuk belajar / studi banding" },
  { pertanyaan: "Apa arti dari 'でんわします'?", jawaban: "menelpon" },
  { pertanyaan: "Apa arti dari 'おぼえます'?", jawaban: "mengingat / menghafal" },
  { pertanyaan: "Apa arti dari 'わすれます'?", jawaban: "melupakan" },
  { pertanyaan: "Apa arti dari 'なくします'?", jawaban: "kehilangan" },
  { pertanyaan: "Apa arti dari 'はらいます'?", jawaban: "membayar" },
  { pertanyaan: "Apa arti dari 'かえします'?", jawaban: "mengembalikan" },
  { pertanyaan: "Apa arti dari 'でかけます'?", jawaban: "keluar (pergi)" },
  { pertanyaan: "Apa arti dari 'ぬぎます'?", jawaban: "melepas (pakaian, sepatu, dsb.)" },
  { pertanyaan: "Apa arti dari 'もっていきます'?", jawaban: "membawa (pergi)" },
  { pertanyaan: "Apa arti dari 'もってきます'?", jawaban: "membawa (datang)" },
  { pertanyaan: "Apa arti dari 'しんぱいします'?", jawaban: "khawatir" },
  { pertanyaan: "Apa arti dari 'しゅっちょうします'?", jawaban: "dinas / perjalanan bisnis" },
  { pertanyaan: "Apa arti dari 'のみます'?", jawaban: "minum" },
  { pertanyaan: "Apa arti dari 'はいります'?", jawaban: "masuk" },
  { pertanyaan: "Apa arti dari 'できます'?", jawaban: "bisa / dapat melakukan" },
  { pertanyaan: "Apa arti dari 'あらいます'?", jawaban: "mencuci" },
  { pertanyaan: "Apa arti dari 'ひきます'?", jawaban: "memainkan (alat musik)" },
  { pertanyaan: "Apa arti dari 'うたいます'?", jawaban: "menyanyi" },
  { pertanyaan: "Apa arti dari 'あつめます'?", jawaban: "mengumpulkan" },
  { pertanyaan: "Apa arti dari 'すてます'?", jawaban: "membuang" },
  { pertanyaan: "Apa arti dari 'うんてんします'?", jawaban: "menyetir / mengemudi" },
  { pertanyaan: "Apa arti dari 'よやくします'?", jawaban: "memesan / reservasi" },
  { pertanyaan: "Apa arti dari 'のぼります'?", jawaban: "mendaki / naik" },
  { pertanyaan: "Apa arti dari 'とまります'?", jawaban: "menginap / berhenti" },
  { pertanyaan: "Apa arti dari 'そうじします'?", jawaban: "membersihkan" },
  { pertanyaan: "Apa arti dari 'せんたくします'?", jawaban: "mencuci (pakaian)" },
  { pertanyaan: "Apa arti dari 'なります'?", jawaban: "menjadi" },
  { pertanyaan: "Apa arti dari 'いります'?", jawaban: "memerlukan / butuh" },
  { pertanyaan: "Apa arti dari 'しらべます'?", jawaban: "memeriksa / mencari tahu" },
  { pertanyaan: "Apa arti dari 'しゅうりします'?", jawaban: "memperbaiki / servis" },
  { pertanyaan: "Apa arti dari 'おもいます'?", jawaban: "berpikir / merasa / berpendapat" },
  { pertanyaan: "Apa arti dari 'いいます'?", jawaban: "mengatakan" },
  { pertanyaan: "Apa arti dari 'かちます'?", jawaban: "menang" },
  { pertanyaan: "Apa arti dari 'まけます'?", jawaban: "kalah" },
  { pertanyaan: "Apa arti dari 'あります'?", jawaban: "ada (benda mati / acara / kepemilikan)" },
  { pertanyaan: "Apa arti dari 'やくにたちます'?", jawaban: "bermanfaat / berguna" },
  { pertanyaan: "Apa arti dari 'うごきます'?", jawaban: "bergerak" },
  { pertanyaan: "Apa arti dari 'やめます'?", jawaban: "berhenti / keluar (kerja, organisasi)" },
  { pertanyaan: "Apa arti dari 'きをつけます'?", jawaban: "berhati-hati" },
  { pertanyaan: "Apa arti dari 'りゅうがくします'?", jawaban: "belajar di luar negeri" },
  { pertanyaan: "Apa arti dari 'きます'?", jawaban: "memakai (bagian atas tubuh)" },
  { pertanyaan: "Apa arti dari 'はきます'?", jawaban: "memakai (bagian bawah tubuh)" },
  { pertanyaan: "Apa arti dari 'かぶります'?", jawaban: "memakai (di kepala)" },
  { pertanyaan: "Apa arti dari 'かけます'?", jawaban: "memakai (kacamata)" },
  { pertanyaan: "Apa arti dari 'します'?", jawaban: "memakai (aksesoris), melakukan" },
  { pertanyaan: "Apa arti dari 'うまれます'?", jawaban: "lahir" },
  { pertanyaan: "Apa arti dari 'ききます'?", jawaban: "bertanya (kepada)" },
  { pertanyaan: "Apa arti dari 'まわします'?", jawaban: "memutar" },
  { pertanyaan: "Apa arti dari 'ひきます'?", jawaban: "menarik" },
  { pertanyaan: "Apa arti dari 'かえます'?", jawaban: "mengubah" },
  { pertanyaan: "Apa arti dari 'さわります'?", jawaban: "menyentuh" },
  { pertanyaan: "Apa arti dari 'でます'?", jawaban: "keluar (misal: uang keluar dari mesin ATM)" },
  { pertanyaan: "Apa arti dari 'あるきます'?", jawaban: "berjalan" },
  { pertanyaan: "Apa arti dari 'わたります'?", jawaban: "menyeberang" },
  { pertanyaan: "Apa arti dari 'まがります'?", jawaban: "belok" },
  { pertanyaan: "Apa arti dari 'くれます'?", jawaban: "memberi (kepada saya)" },
  { pertanyaan: "Apa arti dari 'なおします'?", jawaban: "memperbaiki" },
  { pertanyaan: "Apa arti dari 'つれていきます'?", jawaban: "mengantar / membawa (orang pergi)" },
  { pertanyaan: "Apa arti dari 'つれてきます'?", jawaban: "mengajak / membawa (orang datang)" },
  { pertanyaan: "Apa arti dari 'おくります'?", jawaban: "mengantar (orang)" },
  { pertanyaan: "Apa arti dari 'しょうかいします'?", jawaban: "memperkenalkan" },
  { pertanyaan: "Apa arti dari 'あんないします'?", jawaban: "menunjukkan jalan / mengantar keliling" },
  { pertanyaan: "Apa arti dari 'せつめいします'?", jawaban: "menjelaskan" }
];
