window.soalKuis = [
  {
    //bab13
    pertanyaan: "遊びます,あそびます,Asobimasu",
    bentukTe: "遊んで,あそんで,Asonde",
    bentukTa: "遊んだ,あそんだ,Asonda",
    bentukU: "遊ぶ,あそぶ,Asobu",
    bentukMasu: "遊びます,あそびます,Asobimasu",
    bentukNai: "遊ばない,あそばない,Asobanai",
    bentukVolitional: "遊ぼう,あそぼう,Asobou",
    bentukImperative: "遊べ,あそべ,Asobe",
    bentukConditional: "遊べば,あそべば,Asobeba"
  },
  {
    pertanyaan: "泳ぎます,およぎます,Oyogimasu",
    bentukTe: "泳いで,およいで,Oyoi de",
    bentukTa: "泳いだ,およいだ,Oyoida",
    bentukU: "泳ぐ,およぐ,Oyogu",
    bentukMasu: "泳ぎます,およぎます,Oyogimasu",
    bentukNai: "泳がない,およがない,Oyoganai",
    bentukVolitional: "泳ごう,およごう,Oyogou",
    bentukImperative: "泳げ,およげ,Oyoge",
    bentukConditional: "泳げば,およげば,Oyogeba"
  },
  {
    pertanyaan: "迎えます,むかえます,Mukaemasu",
    bentukTe: "迎えて,むかえて,Mukaete",
    bentukTa: "迎えた,むかえた,Mukaeta",
    bentukU: "迎える,むかえる,Mukaeru",
    bentukMasu: "迎えます,むかえます,Mukaemasu",
    bentukNai: "迎えない,むかえない,Mukaenai",
    bentukVolitional: "迎えよう,むかえよう,Mukaeyou",
    bentukImperative: "迎えろ,むかえろ,Mukaero",
    bentukConditional: "迎えれば,むかえれば,Mukaereba"
  },
  {
    pertanyaan: "疲れます,つかれます,Tsukaremasu",
    bentukTe: "疲れて,つかれて,Tsukarete",
    bentukTa: "疲れた,つかれた,Tsukareta",
    bentukU: "疲れる,つかれる,Tsukareru",
    bentukMasu: "疲れます,つかれます,Tsukaremasu",
    bentukNai: "疲れない,つかれない,Tsukarenai",
    bentukVolitional: "疲れよう,つかれよう,Tsukareyou",
    bentukImperative: "疲れろ,つかれろ,Tsukarero",
    bentukConditional: "疲れれば,つかれれば,Tsukarereba"
  },
  {
    pertanyaan: "結婚します,けっこんします,Kekkon shimasu",
    bentukTe: "結婚して,けっこんして,Kekkon shite",
    bentukTa: "結婚した,けっこんした,Kekkon shita",
    bentukU: "結婚する,けっこんする,Kekkon suru",
    bentukMasu: "結婚します,けっこんします,Kekkon shimasu",
    bentukNai: "結婚しない,けっこんしない,Kekkon shinai",
    bentukVolitional: "結婚しよう,けっこんしよう,Kekkon shiyou",
    bentukImperative: "結婚しろ,けっこんしろ,Kekkon shiro",
    bentukConditional: "結婚すれば,けっこんすれば,Kekkon sureba"
  },
  {
    pertanyaan: "買い物します,かいものします,Kaikmono shimasu",
    bentukTe: "買い物して,かいものして,Kaikmono shite",
    bentukTa: "買い物した,かいものした,Kaikmono shita",
    bentukU: "買い物する,かいものする,Kaikmono suru",
    bentukMasu: "買い物します,かいものします,Kaikmono shimasu",
    bentukNai: "買い物しない,かいものしない,Kaikmono shinai",
    bentukVolitional: "買い物しよう,かいものしよう,Kaikmono shiyou",
    bentukImperative: "買い物しろ,かいものしろ,Kaikmono shiro",
    bentukConditional: "買い物すれば,かいものすれば,Kaikmono sureba"
  },
  {
    pertanyaan: "食事します,しょくじします,Shokuji shimasu",
    bentukTe: "食事して,しょくじして,Shokuji shite",
    bentukTa: "食事した,しょくじした,Shokuji shita",
    bentukU: "食事する,しょくじする,Shokuji suru",
    bentukMasu: "食事します,しょくじします,Shokuji shimasu",
    bentukNai: "食事しない,しょくじしない,Shokuji shinai",
    bentukVolitional: "食事しよう,しょくじしよう,Shokuji shiyou",
    bentukImperative: "食事しろ,しょくじしろ,Shokuji shiro",
    bentukConditional: "食事すれば,しょくじすれば,Shokuji sureba"
  },
  {
    pertanyaan: "散歩します,さんぽします,Sanpo shimasu",
    bentukTe: "散歩して,さんぽして,Sanpo shite",
    bentukTa: "散歩した,さんぽした,Sanpo shita",
    bentukU: "散歩する,さんぽする,Sanpo suru",
    bentukMasu: "散歩します,さんぽします,Sanpo shimasu",
    bentukNai: "散歩しない,さんぽしない,Sanpo shinai",
    bentukVolitional: "散歩しよう,さんぽしよう,Sanpo shiyou",
    bentukImperative: "散歩しろ,さんぽしろ,Sanpo shiro",
    bentukConditional: "散歩すれば,さんぽすれば,Sanpo sureba"
  },
  //Bab14
  {
    pertanyaan: "つけます,つけます,Tsukemasu",
    bentukTe: "つけて,つけて,Tsukete",
    bentukTa: "つけた,つけた,Tsuketa",
    bentukU: "つける,つける,Tsukeru",
    bentukMasu: "つけます,つけます,Tsukemasu",
    bentukNai: "つけない,つけない,Tsukenai",
    bentukVolitional: "つけよう,つけよう,Tsukeyou",
    bentukImperative: "つけろ,つけろ,Tsukero",
    bentukConditional: "つければ,つければ,Tsukereba"
  },
  {
    pertanyaan: "消します,けします,Keshimasu",
    bentukTe: "消して,けして,Keshite",
    bentukTa: "消した,けした,Keshita",
    bentukU: "消す,けす,Kesu",
    bentukMasu: "消します,けします,Keshimasu",
    bentukNai: "消さない,けさない,Kesanai",
    bentukVolitional: "消そう,けそう,Kesou",
    bentukImperative: "消せ,けせ,Kese",
    bentukConditional: "消せば,けせば,Keseba"
  },
  {
    pertanyaan: "開けます,あけます,Akemasu",
    bentukTe: "開けて,あけて,Akete",
    bentukTa: "開けた,あけた,Aketa",
    bentukU: "開ける,あける,Akeru",
    bentukMasu: "開けます,あけます,Akemasu",
    bentukNai: "開けない,あけない,Akenai",
    bentukVolitional: "開けよう,あけよう,Akeyou",
    bentukImperative: "開けろ,あけろ,Ake ro",
    bentukConditional: "開ければ,あければ,Akereba"
  },
  {
    pertanyaan: "閉めます,しめます,Shimemasu",
    bentukTe: "閉めて,しめて,Shimete",
    bentukTa: "閉めた,しめた,Shimeta",
    bentukU: "閉める,しめる,Shimeru",
    bentukMasu: "閉めます,しめます,Shimemasu",
    bentukNai: "閉めない,しめない,Shimenai",
    bentukVolitional: "閉めよう,しめよう,Shimeyou",
    bentukImperative: "閉めろ,しめろ,Shimero",
    bentukConditional: "閉めれば,しめれば,Shimereba"
  },
  {
    pertanyaan: "急ぎます,いそぎます,Isogimasu",
    bentukTe: "急いで,いそいで,Isoide",
    bentukTa: "急いだ,いそいだ,Isoida",
    bentukU: "急ぐ,いそぐ,Isogu",
    bentukMasu: "急ぎます,いそぎます,Isogimasu",
    bentukNai: "急がない,いそがない,Isoganai",
    bentukVolitional: "急ごう,いそごう,Isogou",
    bentukImperative: "急げ,いそげ,Isoge",
    bentukConditional: "急げば,いそげば,Isogeba"
  },
  {
    pertanyaan: "待ちます,まちます,Machimasu",
    bentukTe: "待って,まって,Matte",
    bentukTa: "待った,まった,Matta",
    bentukU: "待つ,まつ,Matsu",
    bentukMasu: "待ちます,まちます,Machimasu",
    bentukNai: "待たない,またない,Matanai",
    bentukVolitional: "待とう,まとう,Matou",
    bentukImperative: "待て,まて,Mate",
    bentukConditional: "待てば,まてば,Mateba"
  },
  {
    pertanyaan: "持ちます,もちます,Mochimasu",
    bentukTe: "持って,もって,Motte",
    bentukTa: "持った,もった,Motta",
    bentukU: "持つ,もつ,Motsu",
    bentukMasu: "持ちます,もちます,Mochimasu",
    bentukNai: "持たない,またない,Motanai",
    bentukVolitional: "持とう,もとう,Motou",
    bentukImperative: "持て,もて,Mote",
    bentukConditional: "持てば,もてば,Moteba"
  },
  {
    pertanyaan: "取ります,とります,Torimasu",
    bentukTe: "取って,とって,Totte",
    bentukTa: "取った,とった,Totta",
    bentukU: "取る,とる,Toru",
    bentukMasu: "取ります,とります,Torimasu",
    bentukNai: "取らない,とらない,Toranai",
    bentukVolitional: "取ろう,とろう,Torou",
    bentukImperative: "取れ,とれ,Tore",
    bentukConditional: "取れば,とれば,Toreba"
  },
  {
    pertanyaan: "手伝います,てつだいます,Tetsudaimasu",
    bentukTe: "手伝って,てつだって,Tetsudatte",
    bentukTa: "手伝った,てつだった,Tetsudatta",
    bentukU: "手伝う,てつだう,Tetsudau",
    bentukMasu: "手伝います,てつだいます,Tetsudaimasu",
    bentukNai: "手伝わない,てつだわない,Tetsudawanai",
    bentukVolitional: "手伝おう,てつだおう,Tetsudaou",
    bentukImperative: "手伝え,てつだえ,Tetsudae",
    bentukConditional: "手伝えば,てつだえば,Tetsudaeba"
  },
  {
    pertanyaan: "呼びます,よびます,Yobimasu",
    bentukTe: "呼んで,よんで,Yonde",
    bentukTa: "呼んだ,よんだ,Yonda",
    bentukU: "呼ぶ,よぶ,Yobu",
    bentukMasu: "呼びます,よびます,Yobimasu",
    bentukNai: "呼ばない,よばない,Yobanai",
    bentukVolitional: "呼ぼう,よぼう,Yobou",
    bentukImperative: "呼べ,よべ,Yobe",
    bentukConditional: "呼べば,よべば,Yobeba"
  },
  {
    pertanyaan: "話します,はなします,Hanashimasu",
    bentukTe: "話して,はなして,Hanashite",
    bentukTa: "話した,はなした,Hanashita",
    bentukU: "話す,はなす,Hanasu",
    bentukMasu: "話します,はなします,Hanashimasu",
    bentukNai: "話さない,はなさない,Hanasanai",
    bentukVolitional: "話そう,はなそう,Hanasou",
    bentukImperative: "話せ,はなせ,Hanase",
    bentukConditional: "話せば,はなせば,Hanaseba"
  },
  {
    pertanyaan: "使います,つかいます,Tsukaimasu",
    bentukTe: "使って,つかって,Tsukatte",
    bentukTa: "使った,つかった,Tsukatta",
    bentukU: "使う,つかう,Tsukau",
    bentukMasu: "使います,つかいます,Tsukaimasu",
    bentukNai: "使わない,つかわない,Tsukawanai",
    bentukVolitional: "使おう,つかおう,Tsukaou",
    bentukImperative: "使え,つかえ,Tsukae",
    bentukConditional: "使えば,つかえば,Tsukaeba"
  },
  {
    pertanyaan: "止めます,とめます,Tomemasu",
    bentukTe: "止めて,とめて,Tomete",
    bentukTa: "止めた,とめた,Tometa",
    bentukU: "止める,とめる,Tomeru",
    bentukMasu: "止めます,とめます,Tomemasu",
    bentukNai: "止めない,とめない,Tomenai",
    bentukVolitional: "止めよう,とめよう,Tomeyou",
    bentukImperative: "止めろ,とめろ,Tomero",
    bentukConditional: "止めれば,とめれば,Tomereba"
  },
  {
    pertanyaan: "見せます,みせます,Misemasu",
    bentukTe: "見せて,みせて,Misete",
    bentukTa: "見せた,みせた,Miseta",
    bentukU: "見せる,みせる,Miseru",
    bentukMasu: "見せます,みせます,Misemasu",
    bentukNai: "見せない,みせない,Misenai",
    bentukVolitional: "見せよう,みせよう,Miseyou",
    bentukImperative: "見せろ,みせろ,Misero",
    bentukConditional: "見せれば,みせれば,Misereba"
  },
  {
    pertanyaan: "教えます,おしえます,Oshiemasu",
    bentukTe: "教えて,おしえて,Oshiete",
    bentukTa: "教えた,おしえた,Oshieta",
    bentukU: "教える,おしえる,Oshieru",
    bentukMasu: "教えます,おしえます,Oshiemasu",
    bentukNai: "教えない,おしえない,Oshienai",
    bentukVolitional: "教えよう,おしえよう,Oshieyou",
    bentukImperative: "教えろ,おしえろ,Oshiero",
    bentukConditional: "教えれば,おしえれば,Oshiereba"
  },
  {
    pertanyaan: "座ります,すわります,Suwarimasu",
    bentukTe: "座って,すわって,Suwatte",
    bentukTa: "座った,すわった,Suwatta",
    bentukU: "座る,すわる,Suwaru",
    bentukMasu: "座ります,すわります,Suwarimasu",
    bentukNai: "座らない,すわらない,Suwaranai",
    bentukVolitional: "座ろう,すわろう,Suwarou",
    bentukImperative: "座れ,すわれ,Suware",
    bentukConditional: "座れば,すわれば,Suwareba"
  },
  {
    pertanyaan: "立ちます,たちます,Tachimasu",
    bentukTe: "立って,たって,Tatte",
    bentukTa: "立った,たった,Tatta",
    bentukU: "立つ,たつ,Tatsu",
    bentukMasu: "立ちます,たちます,Tachimasu",
    bentukNai: "立たない,たたない,Tatanai",
    bentukVolitional: "立とう,たとう,Tatou",
    bentukImperative: "立て,たて,Tate",
    bentukConditional: "立てば,たてば,Tateba"
  },
  {
    pertanyaan: "入ります,はいります,Hairimasu",
    bentukTe: "入って,はいって,Haitte",
    bentukTa: "入った,はいった,Haitta",
    bentukU: "入る,はいる,Hairu",
    bentukMasu: "入ります,はいります,Hairimasu",
    bentukNai: "入らない,はいらない,Hairanai",
    bentukVolitional: "入ろう,はいろう,Hairou",
    bentukImperative: "入れ,はいれ,Haire",
    bentukConditional: "入れば,はいれば,Haireba"
  },
  {
    pertanyaan: "出ます,でます,Demasu",
    bentukTe: "出て,でて,Dete",
    bentukTa: "出た,でた,Deta",
    bentukU: "出る,でる,Deru",
    bentukMasu: "出ます,でます,Demasu",
    bentukNai: "出ない,でない,Denai",
    bentukVolitional: "出よう,でよう,Deyou",
    bentukImperative: "出ろ,でろ,Dero",
    bentukConditional: "出れば,でれば,Dereba"
  },
  {
    pertanyaan: "降ります,ふります,Furimasu",
    bentukTe: "降って,ふって,Futte",
    bentukTa: "降った,ふった,Futta",
    bentukU: "降る,ふる,Furu",
    bentukMasu: "降ります,ふります,Furimasu",
    bentukNai: "降らない,ふらない,Furanai",
    bentukVolitional: "降ろう,ふろう,Furou",
    bentukImperative: "降れ,ふれ,Fure",
    bentukConditional: "降れば,ふれば,Fureba"
  },
  {
    pertanyaan: "コビーします,コビーします,Kobī shimasu",
    bentukTe: "コビーして,コビーして,Kobī shite",
    bentukTa: "コビーした,コビーした,Kobī shita",
    bentukU: "コビーする,コビーする,Kobī suru",
    bentukMasu: "コビーします,コビーします,Kobī shimasu",
    bentukNai: "コビーしない,コビーしない,Kobī shinai",
    bentukVolitional: "コビーしよう,コビーしよう,Kobī shiyou",
    bentukImperative: "コビーしろ,コビーしろ,Kobī shiro",
    bentukConditional: "コビーすれば,コビーすれば,Kobī sureba"
  },
  //Bab15
  {
    pertanyaan: "起きます,おきます,Okimasu",
    bentukTe: "起きて,おきて,Okite",
    bentukTa: "起きた,おきた,Okita",
    bentukU: "起きる,おきる,Okiru",
    bentukMasu: "起きます,おきます,Okimasu",
    bentukNai: "起きない,おきない,Okinai",
    bentukVolitional: "起きよう,おきよう,Okiyou",
    bentukImperative: "起きろ,おきろ,Okiro",
    bentukConditional: "起きれば,おきれば,Okireba"
  },
  {
    pertanyaan: "作ります,つくります,Tsukurimasu",
    bentukTe: "作って,つくって,Tsukutte",
    bentukTa: "作った,つくった,Tsukutta",
    bentukU: "作る,つくる,Tsukuru",
    bentukMasu: "作ります,つくります,Tsukurimasu",
    bentukNai: "作らない,つくらない,Tsukuranai",
    bentukVolitional: "作ろう,つくろう,Tsukurou",
    bentukImperative: "作れ,つくれ,Tsukure",
    bentukConditional: "作れば,つくれば,Tsukureba"
  },
  {
    pertanyaan: "売ります,うります,Urimasu",
    bentukTe: "売って,うって,Utte",
    bentukTa: "売った,うった,Utta",
    bentukU: "売る,うる,Uru",
    bentukMasu: "売ります,うります,Urimasu",
    bentukNai: "売らない,うらない,Uranai",
    bentukVolitional: "売ろう,うろう,Urō",
    bentukImperative: "売れ,うれ,Ure",
    bentukConditional: "売れば,うれば,Ureba"
  },
  {
    pertanyaan: "知ります,しります,Shirimasu",
    bentukTe: "知って,しって,Shitte",
    bentukTa: "知った,しった,Shitta",
    bentukU: "知る,しる,Shiru",
    bentukMasu: "知ります,しります,Shirimasu",
    bentukNai: "知らない,しらない,Shiranai",
    bentukVolitional: "知ろう,しろう,Shirou",
    bentukImperative: "知れ,しれ,Shire",
    bentukConditional: "知れば,しれば,Shireba"
  },
  {
    pertanyaan: "住みます,すみます,Sumimasu",
    bentukTe: "住んで,すんで,Sunde",
    bentukTa: "住んだ,すんだ,Sunda",
    bentukU: "住む,すむ,Sumu",
    bentukMasu: "住みます,すみます,Sumimasu",
    bentukNai: "住まない,すまない,Sumanai",
    bentukVolitional: "住もう,すもう,Sumou",
    bentukImperative: "住め,すめ,Sume",
    bentukConditional: "住めば,すめば,Sumeba"
  },
  {
    pertanyaan: "研究します,けんきゅうします,Kenkyū shimasu",
    bentukTe: "研究して,けんきゅうして,Kenkyū shite",
    bentukTa: "研究した,けんきゅうした,Kenkyū shita",
    bentukU: "研究する,けんきゅうする,Kenkyū suru",
    bentukMasu: "研究します,けんきゅうします,Kenkyū shimasu",
    bentukNai: "研究しない,けんきゅうしない,Kenkyū shinai",
    bentukVolitional: "研究しよう,けんきゅうしよう,Kenkyū shiyou",
    bentukImperative: "研究しろ,けんきゅうしろ,Kenkyū shiro",
    bentukConditional: "研究すれば,けんきゅうすれば,Kenkyū sureba"
  },
  //bab16
  {
    pertanyaan: "乗ります,のります,Norimasu",
    bentukTe: "乗って,のって,Notte",
    bentukTa: "乗った,のった,Notta",
    bentukU: "乗る,のる,Noru",
    bentukMasu: "乗ります,のります,Norimasu",
    bentukNai: "乗らない,のらない,Noranai",
    bentukVolitional: "乗ろう,のろう,Norou",
    bentukImperative: "乗れ,のれ,Nore",
    bentukConditional: "乗れば,のれば,Noreba"
  },
  {
    pertanyaan: "おります,おります,Orimasu",
    bentukTe: "降りて,おりて,Orite",
    bentukTa: "降りた,おりた,Orita",
    bentukU: "降りる,おりる,Oriru",
    bentukMasu: "おります,おります,Orimasu",
    bentukNai: "降りない,おりない,Orinai",
    bentukVolitional: "降りよう,おりよう,Oriyō",
    bentukImperative: "降りろ,おりろ,Oriro",
    bentukConditional: "降りれば,おりれば,Orireba"
  },
  {
    pertanyaan: "乗り換えます,のりかえます,Norikaemasu",
    bentukTe: "乗り換えて,のりかえて,Norikaete",
    bentukTa: "乗り換えた,のりかえた,Norikaeta",
    bentukU: "乗り換える,のりかえる,Norikaeru",
    bentukMasu: "乗り換えます,のりかえます,Norikaemasu",
    bentukNai: "乗り換えない,のりかえない,Norikaenai",
    bentukVolitional: "乗り換えよう,のりかえよう,Norikaeyou",
    bentukImperative: "乗り換えろ,のりかえろ,Norikaero",
    bentukConditional: "乗り換えれば,のりかえれば,Norikaereba"
  },
  {
    pertanyaan: "浴びます,あびます,Abimasu",
    bentukTe: "浴びて,あびて,Abite",
    bentukTa: "浴びた,あびた,Abita",
    bentukU: "浴びる,あびる,Abiru",
    bentukMasu: "浴びます,あびます,Abimasu",
    bentukNai: "浴びない,あびない,Abinai",
    bentukVolitional: "浴びよう,あびよう,Abiyou",
    bentukImperative: "浴びろ,あびろ,Abiro",
    bentukConditional: "浴びれば,あびれば,Abireba"
  },
  {
    pertanyaan: "入れます,いれます,Iremasu",
    bentukTe: "入れて,いれて,Irete",
    bentukTa: "入れた,いれた,Ireta",
    bentukU: "入れる,いれる,Ireru",
    bentukMasu: "入れます,いれます,Iremasu",
    bentukNai: "入れない,いれない,Irenai",
    bentukVolitional: "入れよう,いれよう,Ireyou",
    bentukImperative: "入れろ,いれろ,Irero",
    bentukConditional: "入れれば,いれれば,Ireba"
  },
  {
    pertanyaan: "出します,だします,Dashimasu",
    bentukTe: "出して,だして,Dashite",
    bentukTa: "出した,だした,Dashita",
    bentukU: "出す,だす,Dasu",
    bentukMasu: "出します,だします,Dashimasu",
    bentukNai: "出さない,ださない,Dasanai",
    bentukVolitional: "出そう,だそう,Dasou",
    bentukImperative: "出せ,だせ,Dase",
    bentukConditional: "出せば,だせば,Daseba"
  },
  {
    pertanyaan: "下ろします,おろします,Oroshimasu",
    bentukTe: "下ろして,おろして,Oroshite",
    bentukTa: "下ろした,おろした,Oroshita",
    bentukU: "下ろす,おろす,Orosu",
    bentukMasu: "下ろします,おろします,Oroshimasu",
    bentukNai: "下ろさない,おろさない,Orosanai",
    bentukVolitional: "下ろそう,おろそう,Oroshou",
    bentukImperative: "下ろせ,おろせ,Orose",
    bentukConditional: "下ろせば,おろせば,Oroseba"
  },
  {
    pertanyaan: "入ります,はいります,Hairimasu",
    bentukTe: "入って,はいって,Haitte",
    bentukTa: "入った,はいった,Haitta",
    bentukU: "入る,はいる,Hairu",
    bentukMasu: "入ります,はいります,Hairimasu",
    bentukNai: "入らない,はいらない,Hairanai",
    bentukVolitional: "入ろう,はいろう,Hairou",
    bentukImperative: "入れ,はいれ,Ha ire",
    bentukConditional: "入れば,はいれば,Haireba"
  },
  {
    pertanyaan: "出ます,でます,Demasu",
    bentukTe: "出て,でて,Dete",
    bentukTa: "出た,でた,Deta",
    bentukU: "出る,でる,Deru",
    bentukMasu: "出ます,でます,Demasu",
    bentukNai: "出ない,でない,Denai",
    bentukVolitional: "出よう,でよう,Deyou",
    bentukImperative: "出ろ,でろ,Dero",
    bentukConditional: "出れば,でれば,Dereba"
  },
  {
    pertanyaan: "押します,おします,Oshimasu",
    bentukTe: "押して,おして,Oshite",
    bentukTa: "押した,おした,Oshita",
    bentukU: "押す,おす,Osu",
    bentukMasu: "押します,おします,Oshimasu",
    bentukNai: "押さない,おさない,Osanai",
    bentukVolitional: "押そう,おそう,Oshou",
    bentukImperative: "押せ,おせ,Ose",
    bentukConditional: "押せば,おせば,Oseba"
  },
  {
    pertanyaan: "飲みます,のみます,Nomimasu",
    bentukTe: "飲んで,のんで,Nonde",
    bentukTa: "飲んだ,のんだ,Nonda",
    bentukU: "飲む,のむ,Nomu",
    bentukMasu: "飲みます,のみます,Nomimasu",
    bentukNai: "飲まない,のまない,Nomanai",
    bentukVolitional: "飲もう,のもう,Nomou",
    bentukImperative: "飲め,のめ,Nome",
    bentukConditional: "飲めば,のめば,Nomeba"
  },
  {
    pertanyaan: "始めます,はじめます,Hajimemasu",
    bentukTe: "始めて,はじめて,Hajimete",
    bentukTa: "始めた,はじめた,Hajimeta",
    bentukU: "始める,はじめる,Hajimeru",
    bentukMasu: "始めます,はじめます,Hajimemasu",
    bentukNai: "始めない,はじめない,Hajimenai",
    bentukVolitional: "始めよう,はじめよう,Hajimeyou",
    bentukImperative: "始めろ,はじめろ,Hajimero",
    bentukConditional: "始めれば,はじめれば,Hajimereba"
  },
  {
    pertanyaan: "見学します,けんがくします,Kengaku shimasu",
    bentukTe: "見学して,けんがくして,Kengaku shite",
    bentukTa: "見学した,けんがくした,Kengaku shita",
    bentukU: "見学する,けんがくする,Kengaku suru",
    bentukMasu: "見学します,けんがくします,Kengaku shimasu",
    bentukNai: "見学しない,けんがくしない,Kengaku shinai",
    bentukVolitional: "見学しよう,けんがくしよう,Kengaku shiyou",
    bentukImperative: "見学しろ,けんがくしろ,Kengaku shiro",
    bentukConditional: "見学すれば,けんがくすれば,Kengaku sureba"
  },
  {
    pertanyaan: "電話します,でんわします,Denwa shimasu",
    bentukTe: "電話して,でんわして,Denwa shite",
    bentukTa: "電話した,でんわした,Denwa shita",
    bentukU: "電話する,でんわする,Denwa suru",
    bentukMasu: "電話します,でんわします,Denwa shimasu",
    bentukNai: "電話しない,でんわしない,Denwa shinai",
    bentukVolitional: "電話しよう,でんわしよう,Denwa shiyou",
    bentukImperative: "電話しろ,でんわしろ,Denwa shiro",
    bentukConditional: "電話すれば,でんわすれば,Denwa sureba"
  },
  //BAB 17
  {
    pertanyaan: "覚えます,おぼえます,Oboemasu",
    bentukTe: "覚えて,おぼえて,Oboete",
    bentukTa: "覚えた,おぼえた,Oboeta",
    bentukU: "覚える,おぼえる,Oboeru",
    bentukMasu: "覚えます,おぼえます,Oboemasu",
    bentukNai: "覚えない,おぼえない,Oboenai",
    bentukVolitional: "覚えよう,おぼえよう,Oboeyou",
    bentukImperative: "覚えろ,おぼえろ,Oboero",
    bentukConditional: "覚えれば,おぼえれば,Oboereba"
  },
  {
    pertanyaan: "忘れます,わすれます,Wasuremasu",
    bentukTe: "忘れて,わすれて,Wasurete",
    bentukTa: "忘れた,わすれた,Wasureta",
    bentukU: "忘れる,わすれる,Wasureru",
    bentukMasu: "忘れます,わすれます,Wasuremasu",
    bentukNai: "忘れない,わすれない,Wasurenai",
    bentukVolitional: "忘れよう,わすれよう,Wasureyou",
    bentukImperative: "忘れろ,わすれろ,Wasurero",
    bentukConditional: "忘れれば,わすれれば,Wasureba"
  },
  {
    pertanyaan: "無くします,なくします,Nakushimasu",
    bentukTe: "無くして,なくして,Nakushite",
    bentukTa: "無くした,なくした,Nakushita",
    bentukU: "無くす,なくす,Nakusu",
    bentukMasu: "無くします,なくします,Nakushimasu",
    bentukNai: "無くさない,なくさない,Nakusanai",
    bentukVolitional: "無くそう,なくそう,Nakusou",
    bentukImperative: "無くせ,なくせ,Nakuse",
    bentukConditional: "無くせば,なくせば,Nakseba"
  },
  {
    pertanyaan: "払います,はらいます,Haraimasu",
    bentukTe: "払って,はらって,Haratte",
    bentukTa: "払った,はらった,Haratta",
    bentukU: "払う,はらう,Harau",
    bentukMasu: "払います,はらいます,Haraimasu",
    bentukNai: "払わない,はらわない,Harawanai",
    bentukVolitional: "払おう,はらおう,Haraou",
    bentukImperative: "払え,はらえ,Harae",
    bentukConditional: "払えば,はらえば,Haraeba"
  },
  {
    pertanyaan: "返します,かえします,Kaeshimasu",
    bentukTe: "返して,かえして,Kaeshite",
    bentukTa: "返した,かえした,Kaeshita",
    bentukU: "返す,かえす,Kaesu",
    bentukMasu: "返します,かえします,Kaeshimasu",
    bentukNai: "返さない,かえさない,Kaesanai",
    bentukVolitional: "返そう,かえそう,Kaesou",
    bentukImperative: "返せ,かえせ,Kaese",
    bentukConditional: "返せば,かえせば,Kaeseba"
  },
  {
    pertanyaan: "出かけます,でかけます,Dekakemasu",
    bentukTe: "出かけて,でかけて,Dekakete",
    bentukTa: "出かけた,でかけた,Dekaketa",
    bentukU: "出かける,でかける,Dekakeru",
    bentukMasu: "出かけます,でかけます,Dekakemasu",
    bentukNai: "出かけない,でかけない,Dekakenai",
    bentukVolitional: "出かけよう,でかけよう,Dekakeyou",
    bentukImperative: "出かけろ,でかけろ,Dekakero",
    bentukConditional: "出かければ,でかければ,Dekakereba"
  },
  {
    pertanyaan: "脱ぎます,ぬぎます,Nugimasu",
    bentukTe: "脱いで,ぬいで,Nuide",
    bentukTa: "脱いだ,ぬいだ,Nuida",
    bentukU: "脱ぐ,ぬぐ,Nugu",
    bentukMasu: "脱ぎます,ぬぎます,Nugimasu",
    bentukNai: "脱がない,ぬがない,Nuganai",
    bentukVolitional: "脱ごう,ぬごう,Nugou",
    bentukImperative: "脱げ,ぬげ,Nuge",
    bentukConditional: "脱げば,ぬげば,Nugeba"
  },
  {
    pertanyaan: "持って行きます,もっていきます,Motte ikimasu",
    bentukTe: "持って行って,もっていって,Motte itte",
    bentukTa: "持って行った,もっていった,Motte itta",
    bentukU: "持って行く,もっていく,Motte iku",
    bentukMasu: "持って行きます,もっていきます,Motte ikimasu",
    bentukNai: "持って行かない,もっていかない,Motte ikanai",
    bentukVolitional: "持って行こう,もっていこう,Motte ikou",
    bentukImperative: "持って行け,もっていけ,Motte ike",
    bentukConditional: "持って行けば,もっていけば,Motte ikeba"
  },
  {
    pertanyaan: "持って来ます,もってきます,Motte kimasu",
    bentukTe: "持って来て,もってきて,Motte kite",
    bentukTa: "持って来た,もってきた,Motte kita",
    bentukU: "持って来る,もってくる,Motte kuru",
    bentukMasu: "持って来ます,もってきます,Motte kimasu",
    bentukNai: "持って来ない,もってこない,Motte konai",
    bentukVolitional: "持って来よう,もってこよう,Motte koyou",
    bentukImperative: "持って来い,もってこい,Motte koi",
    bentukConditional: "持って来れば,もってくれば,Motte kureba"
  },
  {
    pertanyaan: "心配します,しんぱいします,Shinpai shimasu",
    bentukTe: "心配して,しんぱいして,Shinpai shite",
    bentukTa: "心配した,しんぱいした,Shinpai shita",
    bentukU: "心配する,しんぱいする,Shinpai suru",
    bentukMasu: "心配します,しんぱいします,Shinpai shimasu",
    bentukNai: "心配しない,しんぱいしない,Shinpai shinai",
    bentukVolitional: "心配しよう,しんぱいしよう,Shinpai shiyou",
    bentukImperative: "心配しろ,しんぱいしろ,Shinpai shiro",
    bentukConditional: "心配すれば,しんぱいすれば,Shinpai sureba"
  },
  {
    pertanyaan: "出張します,しゅっちょうします,Shucchou shimasu",
    bentukTe: "出張して,しゅっちょうして,Shucchou shite",
    bentukTa: "出張した,しゅっちょうした,Shucchou shita",
    bentukU: "出張する,しゅっちょうする,Shucchou suru",
    bentukMasu: "出張します,しゅっちょうします,Shucchou shimasu",
    bentukNai: "出張しない,しゅっちょうしない,Shucchou shinai",
    bentukVolitional: "出張しよう,しゅっちょうしよう,Shucchou shiyou",
    bentukImperative: "出張しろ,しゅっちょうしろ,Shucchou shiro",
    bentukConditional: "出張すれば,しゅっちょうすれば,Shucchou sureba"
  },
  {
    pertanyaan: "飲みます,のみます,Nomimasu",
    bentukTe: "飲んで,のんで,Nonde",
    bentukTa: "飲んだ,のんだ,Nonda",
    bentukU: "飲む,のむ,Nomu",
    bentukMasu: "飲みます,のみます,Nomimasu",
    bentukNai: "飲まない,のまない,Nomanai",
    bentukVolitional: "飲もう,のもう,Nomou",
    bentukImperative: "飲め,のめ,Nome",
    bentukConditional: "飲めば,のめば,Nomeba"
  },
  {
    pertanyaan: "入ります,はいります,Hairimasu",
    bentukTe: "入って,はいって,Haitte",
    bentukTa: "入った,はいった,Haitta",
    bentukU: "入る,はいる,Hairu",
    bentukMasu: "入ります,はいります,Hairimasu",
    bentukNai: "入らない,はいらない,Hairanai",
    bentukVolitional: "入ろう,はいろう,Hairou",
    bentukImperative: "入れ,はいれ,Haire",
    bentukConditional: "入れば,はいれば,Haireba"
  },
  //Bab 18
  {
    pertanyaan: "できます,できます,Dekimasu",
    bentukTe: "できて,できて,Dekite",
    bentukTa: "できた,できた,Dekita",
    bentukU: "できる,できる,Dekiru",
    bentukMasu: "できます,できます,Dekimasu",
    bentukNai: "できない,できない,Dekinai",
    bentukVolitional: "できよう,できよう,Dekiyou",
    bentukImperative: "できろ,できろ,Dekiro",
    bentukConditional: "できれば,できれば,Dekireba"
  },
  {
    pertanyaan: "洗います,あらいます,Araimasu",
    bentukTe: "洗って,あらって,Aratte",
    bentukTa: "洗った,あらった,Aratta",
    bentukU: "洗う,あらう,Arau",
    bentukMasu: "洗います,あらいます,Araimasu",
    bentukNai: "洗わない,あらわない,Arawanai",
    bentukVolitional: "洗おう,あらおう,Araou",
    bentukImperative: "洗え,あらえ,Arae",
    bentukConditional: "洗えば,あらえば,Araeba"
  },
  {
    pertanyaan: "弾きます,ひきます,Hikimasu",
    bentukTe: "弾いて,ひいて,Hiite",
    bentukTa: "弾いた,ひいた,Hiita",
    bentukU: "弾く,ひく,Hiku",
    bentukMasu: "弾きます,ひきます,Hikimasu",
    bentukNai: "弾かない,ひかない,Hikanai",
    bentukVolitional: "弾こう,ひこう,Hikou",
    bentukImperative: "弾け,ひけ,Hike",
    bentukConditional: "弾けば,ひけば,Hikeba"
  },
  {
    pertanyaan: "歌います,うたいます,Utaimasu",
    bentukTe: "歌って,うたって,Utatte",
    bentukTa: "歌った,うたった,Utatta",
    bentukU: "歌う,うたう,Utau",
    bentukMasu: "歌います,うたいます,Utaimasu",
    bentukNai: "歌わない,うたわない,Utawanai",
    bentukVolitional: "歌おう,うたおう,Utaou",
    bentukImperative: "歌え,うたえ,Utae",
    bentukConditional: "歌えば,うたえば,Utaeba"
  },
  {
    pertanyaan: "集めます,あつめます,Atsumemasu",
    bentukTe: "集めて,あつめて,Atsumete",
    bentukTa: "集めた,あつめた,Atsumeta",
    bentukU: "集める,あつめる,Atsumeru",
    bentukMasu: "集めます,あつめます,Atsumemasu",
    bentukNai: "集めない,あつめない,Atsumenai",
    bentukVolitional: "集めよう,あつめよう,Atsumeyou",
    bentukImperative: "集めろ,あつめろ,Atsumero",
    bentukConditional: "集めれば,あつめれば,Atsumereba"
  },
  {
    pertanyaan: "捨てます,すてます,Sutemasu",
    bentukTe: "捨てて,すてて,Sutete",
    bentukTa: "捨てた,すてた,Suteta",
    bentukU: "捨てる,すてる,Suteru",
    bentukMasu: "捨てます,すてます,Sutemasu",
    bentukNai: "捨てない,すてない,Sutenai",
    bentukVolitional: "捨てよう,すてよう,Suteyou",
    bentukImperative: "捨てろ,すてろ,Sutero",
    bentukConditional: "捨てれば,すてれば,Sutereba"
  },
  {
    pertanyaan: "運転します,うんてんします,Unten shimasu",
    bentukTe: "運転して,うんてんして,Unten shite",
    bentukTa: "運転した,うんてんした,Unten shita",
    bentukU: "運転する,うんてんする,Unten suru",
    bentukMasu: "運転します,うんてんします,Unten shimasu",
    bentukNai: "運転しない,うんてんしない,Unten shinai",
    bentukVolitional: "運転しよう,うんてんしよう,Unten shiyou",
    bentukImperative: "運転しろ,うんてんしろ,Unten shiro",
    bentukConditional: "運転すれば,うんてんすれば,Unten sureba"
  },
  {
    pertanyaan: "予約します,よやくします,Yoyaku shimasu",
    bentukTe: "予約して,よやくして,Yoyaku shite",
    bentukTa: "予約した,よやくした,Yoyaku shita",
    bentukU: "予約する,よやくする,Yoyaku suru",
    bentukMasu: "予約します,よやくします,Yoyaku shimasu",
    bentukNai: "予約しない,よやくしない,Yoyaku shinai",
    bentukVolitional: "予約しよう,よやくしよう,Yoyaku shiyou",
    bentukImperative: "予約しろ,よやくしろ,Yoyaku shiro",
    bentukConditional: "予約すれば,よやくすれば,Yoyaku sureba"
  },
  //BAB 19
  {
    pertanyaan: "登ります,のぼります,Noborimasu",
    bentukTe: "登って,のぼって,Nobotte",
    bentukTa: "登った,のぼった,Nobotta",
    bentukU: "登る,のぼる,Noboru",
    bentukMasu: "登ります,のぼります,Noborimasu",
    bentukNai: "登らない,のぼらない,Noboranai",
    bentukVolitional: "登ろう,のぼろう,Noborou",
    bentukImperative: "登れ,のぼれ,Nobore",
    bentukConditional: "登れば,のぼれば,Noboreba"
  },
  {
    pertanyaan: "泊まります,とまります,Tomarimasu",
    bentukTe: "泊まって,とまって,Tomatte",
    bentukTa: "泊まった,とまった,Tomatta",
    bentukU: "泊まる,とまる,Tomaru",
    bentukMasu: "泊まります,とまります,Tomarimasu",
    bentukNai: "泊まらない,とまらない,Tomaranai",
    bentukVolitional: "泊まろう,とまろう,Tomarou",
    bentukImperative: "泊まれ,とまれ,Tomare",
    bentukConditional: "泊まれば,とまれば,Tomareba"
  },
  {
    pertanyaan: "掃除します,そうじします,Sōji shimasu",
    bentukTe: "掃除して,そうじして,Sōji shite",
    bentukTa: "掃除した,そうじした,Sōji shita",
    bentukU: "掃除する,そうじする,Sōji suru",
    bentukMasu: "掃除します,そうじします,Sōji shimasu",
    bentukNai: "掃除しない,そうじしない,Sōji shinai",
    bentukVolitional: "掃除しよう,そうじしよう,Sōji shiyou",
    bentukImperative: "掃除しろ,そうじしろ,Sōji shiro",
    bentukConditional: "掃除すれば,そうじすれば,Sōji sureba"
  },
  {
    pertanyaan: "洗濯します,せんたくします,Sentaku shimasu",
    bentukTe: "洗濯して,せんたくして,Sentaku shite",
    bentukTa: "洗濯した,せんたくした,Sentaku shita",
    bentukU: "洗濯する,せんたくする,Sentaku suru",
    bentukMasu: "洗濯します,せんたくします,Sentaku shimasu",
    bentukNai: "洗濯しない,せんたくしない,Sentaku shinai",
    bentukVolitional: "洗濯しよう,せんたくしよう,Sentaku shiyou",
    bentukImperative: "洗濯しろ,せんたくしろ,Sentaku shiro",
    bentukConditional: "洗濯すれば,せんたくすれば,Sentaku sureba"
  },
  {
    pertanyaan: "なります,なります,Narimasu",
    bentukTe: "なって,なって,Natte",
    bentukTa: "なった,なった,Natta",
    bentukU: "なる,なる,Naru",
    bentukMasu: "なります,なります,Narimasu",
    bentukNai: "ならない,ならない,Naranai",
    bentukVolitional: "なろう,なろう,Narou",
    bentukImperative: "なれ,なれ,Nare",
    bentukConditional: "なれば,なれば,Nareba"
  },
  //BAB 20
  {
    pertanyaan: "要ります,いります,Irimasu",
    bentukTe: "要って,いって,Itte",
    bentukTa: "要った,いった,Itta",
    bentukU: "要る,いる,Iru",
    bentukMasu: "要ります,いります,Irimasu",
    bentukNai: "要らない,いらない,Iranai",
    bentukVolitional: "要ろう,いろう,Irou",
    bentukImperative: "要れ,いれ,Ire",
    bentukConditional: "要れば,いれば,Ireba"
  },
  {
    pertanyaan: "調べます,しらべます,Shirabemasu",
    bentukTe: "調べて,しらべて,Shirabete",
    bentukTa: "調べた,しらべた,Shirabeta",
    bentukU: "調べる,しらべる,Shiraberu",
    bentukMasu: "調べます,しらべます,Shirabemasu",
    bentukNai: "調べない,しらべない,Shirabenai",
    bentukVolitional: "調べよう,しらべよう,Shirabeyou",
    bentukImperative: "調べろ,しらべろ,Shirabero",
    bentukConditional: "調べれば,しらべれば,Shirabereba"
  },
  {
    pertanyaan: "修理します,しゅうりします,Shūri shimasu",
    bentukTe: "修理して,しゅうりして,Shūri shite",
    bentukTa: "修理した,しゅうりした,Shūri shita",
    bentukU: "修理する,しゅうりする,Shūri suru",
    bentukMasu: "修理します,しゅうりします,Shūri shimasu",
    bentukNai: "修理しない,しゅうりしない,Shūri shinai",
    bentukVolitional: "修理しよう,しゅうりしよう,Shūri shiyou",
    bentukImperative: "修理しろ,しゅうりしろ,Shūri shiro",
    bentukConditional: "修理すれば,しゅうりすれば,Shūri sureba"
  },
  //BAB 21
  {
    pertanyaan: "思います,おもいます,Omoimasu",
    bentukTe: "思って,おもって,Omotte",
    bentukTa: "思った,おもった,Omotta",
    bentukU: "思う,おもう,Omou",
    bentukMasu: "思います,おもいます,Omoimasu",
    bentukNai: "思わない,おもわない,Omowanai",
    bentukVolitional: "思おう,おもおう,Omou",
    bentukImperative: "思え,おもえ,Omoe",
    bentukConditional: "思えば,おもえば,Omoeba"
  },
  {
    pertanyaan: "言います,いいます,Iimasu",
    bentukTe: "言って,いって,Itte",
    bentukTa: "言った,いった,Itta",
    bentukU: "言う,いう,Iu",
    bentukMasu: "言います,いいます,Iimasu",
    bentukNai: "言わない,いわない,Iwanai",
    bentukVolitional: "言おう,いおう,Iou",
    bentukImperative: "言え,いえ,Ie",
    bentukConditional: "言えば,いえば,Ieba"
  },
  {
    pertanyaan: "勝ちます,かちます,Kachimasu",
    bentukTe: "勝って,かって,Katte",
    bentukTa: "勝った,かった,Katta",
    bentukU: "勝つ,かつ,Katsu",
    bentukMasu: "勝ちます,かちます,Kachimasu",
    bentukNai: "勝たない,かたない,Katanai",
    bentukVolitional: "勝とう,かとう,Katou",
    bentukImperative: "勝て,かて,Kate",
    bentukConditional: "勝てば,かてば,Kateba"
  },
  {
    pertanyaan: "負けます,まけます,Makemasu",
    bentukTe: "負けて,まけて,Makete",
    bentukTa: "負けた,まけた,Maketa",
    bentukU: "負ける,まける,Makeru",
    bentukMasu: "負けます,まけます,Makemasu",
    bentukNai: "負けない,まけない,Makenai",
    bentukVolitional: "負けよう,まけよう,Makeyou",
    bentukImperative: "負けろ,まけろ,Makero",
    bentukConditional: "負ければ,まければ,Makereba"
  },
  {
    pertanyaan: "あります,あります,Arimasu",
    bentukTe: "あって,あって,Atte",
    bentukTa: "あった,あった,Atta",
    bentukU: "ある,ある,Aru",
    bentukMasu: "あります,あります,Arimasu",
    bentukNai: "ない,ない,Nai",
    bentukVolitional: "あろう,あろう,Arou",
    bentukImperative: "あれ,あれ,Are",
    bentukConditional: "あれば,あれば,Areba"
  },
  {
    pertanyaan: "役に立ちます,やくにたちます,Yaku ni tachimasu",
    bentukTe: "役に立って,やくにたって,Yaku ni tatte",
    bentukTa: "役に立った,やくにたった,Yaku ni tatta",
    bentukU: "役に立つ,やくにたつ,Yaku ni tatsu",
    bentukMasu: "役に立ちます,やくにたちます,Yaku ni tachimasu",
    bentukNai: "役に立たない,やくにたたない,Yaku ni tatanai",
    bentukVolitional: "役に立とう,やくにたとう,Yaku ni tatou",
    bentukImperative: "役に立て,やくにたて,Yaku ni tate",
    bentukConditional: "役に立てば,やくにたてば,Yaku ni tateba"
  },
  {
    pertanyaan: "動きます,うごきます,Ugokimasu",
    bentukTe: "動いて,うごいて,Ugoite",
    bentukTa: "動いた,うごいた,Ugoita",
    bentukU: "動く,うごく,Ugoku",
    bentukMasu: "動きます,うごきます,Ugokimasu",
    bentukNai: "動かない,うごかない,Ugokanai",
    bentukVolitional: "動こう,うごこう,Ugokou",
    bentukImperative: "動け,うごけ,Ugoke",
    bentukConditional: "動けば,うごけば,Ugokeba"
  },
  {
    pertanyaan: "やめます,やめます,Yamemasu",
    bentukTe: "やめて,やめて,Yamete",
    bentukTa: "やめた,やめた,Yameta",
    bentukU: "やめる,やめる,Yameru",
    bentukMasu: "やめます,やめます,Yamemasu",
    bentukNai: "やめない,やめない,Yamenai",
    bentukVolitional: "やめよう,やめよう,Yameyou",
    bentukImperative: "やめろ,やめろ,Yamero",
    bentukConditional: "やめれば,やめれば,Yamereba"
  },
  {
    pertanyaan: "気をつけます,きをつけます,Ki o tsukemasu",
    bentukTe: "気をつけて,きをつけて,Ki o tsukete",
    bentukTa: "気をつけた,きをつけた,Ki o tsuketa",
    bentukU: "気をつける,きをつける,Ki o tsukeru",
    bentukMasu: "気をつけます,きをつけます,Ki o tsukemasu",
    bentukNai: "気をつけない,きをつけない,Ki o tsukenai",
    bentukVolitional: "気をつけよう,きをつけよう,Ki o tsukeyou",
    bentukImperative: "気をつけろ,きをつけろ,Ki o tsukero",
    bentukConditional: "気をつければ,きをつければ,Ki o tsukereba"
  },
  {
    pertanyaan: "留学します,りゅうがくします,Ryuugaku shimasu",
    bentukTe: "留学して,りゅうがくして,Ryuugaku shite",
    bentukTa: "留学した,りゅうがくした,Ryuugaku shita",
    bentukU: "留学する,りゅうがくする,Ryuugaku suru",
    bentukMasu: "留学します,りゅうがくします,Ryuugaku shimasu",
    bentukNai: "留学しない,りゅうがくしない,Ryuugaku shinai",
    bentukVolitional: "留学しよう,りゅうがくしよう,Ryuugaku shiyou",
    bentukImperative: "留学しろ,りゅうがくしろ,Ryuugaku shiro",
    bentukConditional: "留学すれば,りゅうがくすれば,Ryuugaku sureba"
  },
  //BAB 22
  {
    pertanyaan: "着ます,きます,Kimasu",
    bentukTe: "着て,きて,Kite",
    bentukTa: "着た,きた,Kita",
    bentukU: "着る,きる,Kiru",
    bentukMasu: "着ます,きます,Kimasu",
    bentukNai: "着ない,きない,Kinai",
    bentukVolitional: "着よう,きよう,Kiyou",
    bentukImperative: "着ろ,きろ,Kiro",
    bentukConditional: "着れば,きれば,Kireba"
  },
  {
    pertanyaan: "履きます,はきます,Hakimasu",
    bentukTe: "履いて,はいて,Haite",
    bentukTa: "履いた,はいた,Haita",
    bentukU: "履く,はく,Haku",
    bentukMasu: "履きます,はきます,Hakimasu",
    bentukNai: "履かない,はかない,Hakanai",
    bentukVolitional: "履こう,はこう,Hakou",
    bentukImperative: "履け,はけ,Hake",
    bentukConditional: "履けば,はけば,Hakeba"
  },
  {
    pertanyaan: "かぶります,かぶります,Kaburimasu",
    bentukTe: "かぶって,かぶって,Kabutte",
    bentukTa: "かぶった,かぶった,Kabutta",
    bentukU: "かぶる,かぶる,Kaburu",
    bentukMasu: "かぶります,かぶります,Kaburimasu",
    bentukNai: "かぶらない,かぶらない,Kaburanai",
    bentukVolitional: "かぶろう,かぶろう,Kaburou",
    bentukImperative: "かぶれ,かぶれ,Kabure",
    bentukConditional: "かぶれば,かぶれば,Kabureba"
  },
  {
    pertanyaan: "かけます,かけます,Kakemasu",
    bentukTe: "かけて,かけて,Kakete",
    bentukTa: "かけた,かけた,Kaketa",
    bentukU: "かける,かける,Kakeru",
    bentukMasu: "かけます,かけます,Kakemasu",
    bentukNai: "かけない,かけない,Kakenai",
    bentukVolitional: "かけよう,かけよう,Kakeyou",
    bentukImperative: "かけろ,かけろ,Kakero",
    bentukConditional: "かければ,かければ,Kakereba"
  },
  {
    pertanyaan: "します,します,Shimasu",
    bentukTe: "して,して,Shite",
    bentukTa: "した,した,Shita",
    bentukU: "する,する,Suru",
    bentukMasu: "します,します,Shimasu",
    bentukNai: "しない,しない,Shinai",
    bentukVolitional: "しよう,しよう,Shiyou",
    bentukImperative: "しろ,しろ,Shiro",
    bentukConditional: "すれば,すれば,Sureba"
  },
  {
    pertanyaan: "生まれます,うまれます,Umaremasu",
    bentukTe: "生まれて,うまれて,Umarete",
    bentukTa: "生まれた,うまれた,Umareta",
    bentukU: "生まれる,うまれる,Umareru",
    bentukMasu: "生まれます,うまれます,Umaremasu",
    bentukNai: "生まれない,うまれない,Umarenai",
    bentukVolitional: "生まれよう,うまれよう,Umareyou",
    bentukImperative: "生まれろ,うまれろ,Umarero",
    bentukConditional: "生まれれば,うまれれば,Umarereba"
  },
  //BAB 23
  {
    pertanyaan: "聞きます,ききます,Kikimasu",
    bentukTe: "聞いて,きいて,Kite",
    bentukTa: "聞いた,きいた,Kita",
    bentukU: "聞く,きく,Kiku",
    bentukMasu: "聞きます,ききます,Kikimasu",
    bentukNai: "聞かない,きかない,Kikanai",
    bentukVolitional: "聞こう,きこう,Kikou",
    bentukImperative: "聞け,きけ,Kike",
    bentukConditional: "聞けば,きけば,Kikeba"
  },
  {
    pertanyaan: "回します,まわします,Mawashimasu",
    bentukTe: "回して,まわして,Mawashite",
    bentukTa: "回した,まわした,Mawashita",
    bentukU: "回す,まわす,Mawasu",
    bentukMasu: "回します,まわします,Mawashimasu",
    bentukNai: "回さない,まわさない,Mawasanai",
    bentukVolitional: "回そう,まわそう,Mawasou",
    bentukImperative: "回せ,まわせ,Mawase",
    bentukConditional: "回せば,まわせば,Mawaseba"
  },
  {
    pertanyaan: "引きます,ひきます,Hikimasu",
    bentukTe: "引いて,ひいて,Hiite",
    bentukTa: "引いた,ひいた,Hiita",
    bentukU: "引く,ひく,Hiku",
    bentukMasu: "引きます,ひきます,Hikimasu",
    bentukNai: "引かない,ひかない,Hikanai",
    bentukVolitional: "引こう,ひこう,Hikou",
    bentukImperative: "引け,ひけ,Hike",
    bentukConditional: "引けば,ひけば,Hikeba"
  },
  {
    pertanyaan: "変えます,かえます,Kaemasu",
    bentukTe: "変えて,かえて,Kaete",
    bentukTa: "変えた,かえた,Kaeta",
    bentukU: "変える,かえる,Kaeru",
    bentukMasu: "変えます,かえます,Kaemasu",
    bentukNai: "変えない,かえない,Kaenai",
    bentukVolitional: "変えよう,かえよう,Kaeyou",
    bentukImperative: "変えろ,かえろ,Kaero",
    bentukConditional: "変えれば,かえれば,Kaereba"
  },
  {
    pertanyaan: "触ります,さわります,Sawarimasu",
    bentukTe: "触って,さわって,Sawatte",
    bentukTa: "触った,さわった,Sawatta",
    bentukU: "触る,さわる,Sawaru",
    bentukMasu: "触ります,さわります,Sawarimasu",
    bentukNai: "触らない,さわらない,Sawaranai",
    bentukVolitional: "触ろう,さわろう,Sawarou",
    bentukImperative: "触れ,さわれ,Saware",
    bentukConditional: "触れば,さわれば,Sawareba"
  },
  {
    pertanyaan: "出ます,でます,Demasu",
    bentukTe: "出て,でて,Dete",
    bentukTa: "出た,でた,Deta",
    bentukU: "出る,でる,Deru",
    bentukMasu: "出ます,でます,Demasu",
    bentukNai: "出ない,でない,Denai",
    bentukVolitional: "出よう,でよう,Deyou",
    bentukImperative: "出ろ,でろ,Dero",
    bentukConditional: "出れば,でれば,Dereba"
  },
  {
    pertanyaan: "歩きます,あるきます,Arukimasu",
    bentukTe: "歩いて,あるいて,Aruite",
    bentukTa: "歩いた,あるいた,Aruita",
    bentukU: "歩く,あるく,Aruku",
    bentukMasu: "歩きます,あるきます,Arukimasu",
    bentukNai: "歩かない,あるかない,Arukanai",
    bentukVolitional: "歩こう,あるこう,Arukou",
    bentukImperative: "歩け,あるけ,Aruke",
    bentukConditional: "歩けば,あるけば,Arukeba"
  },
  {
    pertanyaan: "渡ります,わたります,Watarimasu",
    bentukTe: "渡って,わたって,Watatte",
    bentukTa: "渡った,わたった,Watatta",
    bentukU: "渡る,わたる,Wataru",
    bentukMasu: "渡ります,わたります,Watarimasu",
    bentukNai: "渡らない,わたらない,Wataranai",
    bentukVolitional: "渡ろう,わたろう,Watarou",
    bentukImperative: "渡れ,わたれ,Watare",
    bentukConditional: "渡れば,わたれば,Watareba"
  },
  {
    pertanyaan: "曲がります,まがります,Magarimasu",
    bentukTe: "曲がって,まがって,Magatte",
    bentukTa: "曲がった,まがった,Magatta",
    bentukU: "曲がる,まがる,Magaru",
    bentukMasu: "曲がります,まがります,Magarimasu",
    bentukNai: "曲がらない,まがらない,Magaranai",
    bentukVolitional: "曲がろう,まがろう,Magarou",
    bentukImperative: "曲がれ,まがれ,Magare",
    bentukConditional: "曲がれば,まがれば,Magareba"
  },
  //BAB 24
  {
    pertanyaan: "くれます,くれます,Kuremasu",
    bentukTe: "くれて,くれて,Kurete",
    bentukTa: "くれた,くれた,Kureta",
    bentukU: "くれる,くれる,Kureru",
    bentukMasu: "くれます,くれます,Kuremasu",
    bentukNai: "くれない,くれない,Kurenai",
    bentukVolitional: "くれよう,くれよう,Kureyou",
    bentukImperative: "くれろ,くれろ,Kurero",
    bentukConditional: "くれれば,くれれば,Kurereba"
  },
  {
    pertanyaan: "直します,なおします,Naoshimasu",
    bentukTe: "直して,なおして,Naoshite",
    bentukTa: "直した,なおした,Naoshita",
    bentukU: "直す,なおす,Naosu",
    bentukMasu: "直します,なおします,Naoshimasu",
    bentukNai: "直さない,なおさない,Naosanai",
    bentukVolitional: "直そう,なおそう,Naosou",
    bentukImperative: "直せ,なおせ,Naose",
    bentukConditional: "直せば,なおせば,Naoseba"
  },
  {
    pertanyaan: "連れて行きます,つれていきます,Tsurete ikimasu",
    bentukTe: "連れて行って,つれていって,Tsurete itte",
    bentukTa: "連れて行った,つれていった,Tsurete itta",
    bentukU: "連れて行く,つれていく,Tsurete iku",
    bentukMasu: "連れて行きます,つれていきます,Tsurete ikimasu",
    bentukNai: "連れて行かない,つれていかない,Tsurete ikanai",
    bentukVolitional: "連れて行こう,つれていこう,Tsurete ikou",
    bentukImperative: "連れて行け,つれていけ,Tsurete ike",
    bentukConditional: "連れて行けば,つれていけば,Tsurete ikeba"
  },
  {
    pertanyaan: "連れて来ます,つれてきます,Tsurete kimasu",
    bentukTe: "連れて来て,つれてきて,Tsurete kite",
    bentukTa: "連れて来た,つれてきた,Tsurete kita",
    bentukU: "連れて来る,つれてくる,Tsurete kuru",
    bentukMasu: "連れて来ます,つれてきます,Tsurete kimasu",
    bentukNai: "連れて来ない,つれてこない,Tsurete konai",
    bentukVolitional: "連れて来よう,つれてこよう,Tsurete koyou",
    bentukImperative: "連れて来い,つれてこい,Tsurete koi",
    bentukConditional: "連れて来れば,つれてこれば,Tsurete koreba"
  },
  {
    pertanyaan: "送ります,おくります,Okurimasu",
    bentukTe: "送って,おくって,Okutte",
    bentukTa: "送った,おくった,Okutta",
    bentukU: "送る,おくる,Okuru",
    bentukMasu: "送ります,おくります,Okurimasu",
    bentukNai: "送らない,おくらない,Okuranai",
    bentukVolitional: "送ろう,おくろう,Okurou",
    bentukImperative: "送れ,おくれ,Okure",
    bentukConditional: "送れば,おくれば,Okureba"
  },
  {
    pertanyaan: "紹介します,しょうかいします,Shoukai shimasu",
    bentukTe: "紹介して,しょうかいして,Shoukai shite",
    bentukTa: "紹介した,しょうかいした,Shoukai shita",
    bentukU: "紹介する,しょうかいする,Shoukai suru",
    bentukMasu: "紹介します,しょうかいします,Shoukai shimasu",
    bentukNai: "紹介しない,しょうかいしない,Shoukai shinai",
    bentukVolitional: "紹介しよう,しょうかいしよう,Shoukai shiyou",
    bentukImperative: "紹介しろ,しょうかいしろ,Shoukai shiro",
    bentukConditional: "紹介すれば,しょうかいすれば,Shoukai sureba"
  },
  {
    pertanyaan: "案内します,あんないします,Annai shimasu",
    bentukTe: "案内して,あんないして,Annai shite",
    bentukTa: "案内した,あんないした,Annai shita",
    bentukU: "案内する,あんないする,Annai suru",
    bentukMasu: "案内します,あんないします,Annai shimasu",
    bentukNai: "案内しない,あんないしない,Annai shinai",
    bentukVolitional: "案内しよう,あんないしよう,Annai shiyou",
    bentukImperative: "案内しろ,あんないしろ,Annai shiro",
    bentukConditional: "案内すれば,あんないすれば,Annai sureba"
  },
  {
    pertanyaan: "説明します,せつめいします,Setsumei shimasu",
    bentukTe: "説明して,せつめいして,Setsumei shite",
    bentukTa: "説明した,せつめいした,Setsumei shita",
    bentukU: "説明する,せつめいする,Setsumei suru",
    bentukMasu: "説明します,せつめいします,Setsumei shimasu",
    bentukNai: "説明しない,せつめいしない,Setsumei shinai",
    bentukVolitional: "説明しよう,せつめいしよう,Setsumei shiyou",
    bentukImperative: "説明しろ,せつめいしろ,Setsumei shiro",
    bentukConditional: "説明すれば,せつめいすれば,Setsumei sureba"
  }
];
