window.soalKuis = [
  { "pertanyaan": "Apa arti dari '父（ちち）'?", "jawaban": "Ayah" },
  { "pertanyaan": "Apa arti dari '母（はは）'?", "jawaban": "Ibu" },
  { "pertanyaan": "Apa arti dari '両親・親（りょうしん・おや）'?", "jawaban": "Orang tua" },
  { "pertanyaan": "Apa arti dari '兄（あに）'?", "jawaban": "Kakak laki-laki" },
  { "pertanyaan": "Apa arti dari '姉（あね）'?", "jawaban": "Kakak perempuan" },
  { "pertanyaan": "Apa arti dari '弟（おとうと）'?", "jawaban": "Adik laki-laki" },
  { "pertanyaan": "Apa arti dari '妹（いもうと）'?", "jawaban": "Adik perempuan" },
  { "pertanyaan": "Apa arti dari '兄弟（きょうだい）'?", "jawaban": "Saudara kandung (laki-laki atau campuran)" },
  { "pertanyaan": "Apa arti dari '姉妹（しまい）'?", "jawaban": "Saudara kandung perempuan" },
  { "pertanyaan": "Apa arti dari '祖父（そふ）'?", "jawaban": "Kakek" },
  { "pertanyaan": "Apa arti dari '祖母（そぼ）'?", "jawaban": "Nenek" },
  { "pertanyaan": "Apa arti dari '祖父母（そふぼ）'?", "jawaban": "Kakek-nenek" },
  { "pertanyaan": "Apa arti dari '伯父・叔父（おじ）'?", "jawaban": "Om / Paman" },
  { "pertanyaan": "Apa arti dari '伯母・叔母（おば）'?", "jawaban": "Tante / Bibi" },
  { "pertanyaan": "Apa arti dari '夫・主人（おっと・しゅじん）'?", "jawaban": "Suami" },
  { "pertanyaan": "Apa arti dari '妻（つま）'?", "jawaban": "Istri" },
  { "pertanyaan": "Apa arti dari '息子（むすこ）'?", "jawaban": "Anak laki-laki" },
  { "pertanyaan": "Apa arti dari '娘（むすめ）'?", "jawaban": "Anak perempuan" },
  { "pertanyaan": "Apa arti dari '子供（こども）'?", "jawaban": "Anak" },
  { "pertanyaan": "Apa arti dari '従兄弟・従姉妹（いとこ）'?", "jawaban": "Sepupu" },
  { "pertanyaan": "Apa arti dari '孫（まご）'?", "jawaban": "Cucu" },
  { "pertanyaan": "Apa arti dari '甥・甥っ子（おい・おいっこ）'?", "jawaban": "Keponakan laki-laki" },
  { "pertanyaan": "Apa arti dari '姪・姪っ子（めい・めいっこ）'?", "jawaban": "Keponakan perempuan" },
  { "pertanyaan": "Apa arti dari '義理の両親（ぎりのりょうしん）'?", "jawaban": "Mertua" },
  { "pertanyaan": "Apa arti dari '義理の父・義父（ぎりのちち・ぎふ）'?", "jawaban": "Ayah mertua" },
  { "pertanyaan": "Apa arti dari '義理の母・義母（ぎりのはは・ぎぼ）'?", "jawaban": "Ibu mertua" },
  { "pertanyaan": "Apa arti dari '義理の兄・義兄（ぎりのあに・ぎけい）'?", "jawaban": "Kakak ipar laki-laki" },
  { "pertanyaan": "Apa arti dari '義理の姉・義姉（ぎりのあね・ぎし）'?", "jawaban": "Kakak ipar perempuan" },
  { "pertanyaan": "Apa arti dari '義理の弟・義弟（ぎりのおとうと・ぎてい）'?", "jawaban": "Adik ipar laki-laki" },
  { "pertanyaan": "Apa arti dari '義理の妹・義妹（ぎりのあね・ぎまい）'?", "jawaban": "Adik ipar perempuan" }
];
