window.soalKuis = [
  { pertanyaan: "Apa arti dari 'きれい'?", jawaban: "bersih" },
  { pertanyaan: "Apa arti dari 'げんき'?", jawaban: "sehat" },
  { pertanyaan: "Apa arti dari 'ゆうめい'?", jawaban: "terkenal" },
  { pertanyaan: "Apa arti dari 'しずか'?", jawaban: "tenang" },
  { pertanyaan: "Apa arti dari 'だいじょうぶ'?", jawaban: "baik-baik saja" },
  { pertanyaan: "Apa arti dari '便利'?", jawaban: "praktis" },
  { pertanyaan: "Apa arti dari 'すてき'?", jawaban: "indah" },
  { pertanyaan: "Apa arti dari 'あたたかい'?", jawaban: "hangat" },
  { pertanyaan: "Apa arti dari 'ふるい'?", jawaban: "lama" },
  { pertanyaan: "Apa arti dari 'たかい'?", jawaban: "mahal" },
  { pertanyaan: "Apa arti dari 'わかい'?", jawaban: "muda" },
  { pertanyaan: "Apa arti dari 'ひろい'?", jawaban: "luas" },
  { pertanyaan: "Apa arti dari 'ちいさい'?", jawaban: "kecil" },
  { pertanyaan: "Apa arti dari 'あたまがいい'?", jawaban: "pintar" },
  { pertanyaan: "Apa arti dari 'おおきい'?", jawaban: "besar" },
  { pertanyaan: "Apa arti dari 'たのしい'?", jawaban: "menyenangkan" },
  { pertanyaan: "Apa arti dari 'ねむい'?", jawaban: "mengantuk" },
  { pertanyaan: "Apa arti dari 'さむい'?", jawaban: "dingin" },
  { pertanyaan: "Apa arti dari 'すごい'?", jawaban: "hebat" },
  { pertanyaan: "Apa arti dari 'うるさい'?", jawaban: "berisik" },
  { pertanyaan: "Apa arti dari 'きびしい'?", jawaban: "ketat" },
  { pertanyaan: "Apa arti dari 'おもしろい'?", jawaban: "menarik" },
  { pertanyaan: "Apa arti dari 'たしか'?", jawaban: "pasti" },
  { pertanyaan: "Apa arti dari 'あかるい'?", jawaban: "terang" },
  { pertanyaan: "Apa arti dari 'ひま'?", jawaban: "luang" },
  { pertanyaan: "Apa arti dari 'こわい'?", jawaban: "menakutkan" },
  { pertanyaan: "Apa arti dari 'わるい'?", jawaban: "buruk" },
  { pertanyaan: "Apa arti dari 'せまい'?", jawaban: "sempit" },
  { pertanyaan: "Apa arti dari 'つめたい'?", jawaban: "dingin" },
  { pertanyaan: "Apa arti dari 'ふかい'?", jawaban: "dalam" },
  { pertanyaan: "Apa arti dari 'うつくしい'?", jawaban: "indah" },
  { pertanyaan: "Apa arti dari 'すくない'?", jawaban: "sedikit" },
  { pertanyaan: "Apa arti dari 'しんせつ'?", jawaban: "ramah" },
  { pertanyaan: "Apa arti dari 'みじかい'?", jawaban: "pendek" },
  { pertanyaan: "Apa arti dari 'すずしい'?", jawaban: "sejuk" }
];
