window.soalKuis = [
  { pertanyaan: "Apa arti dari kanji '日'?", jawaban: "hari / matahari" },
  { pertanyaan: "Apa arti dari kanji '一'?", jawaban: "satu" },
  { pertanyaan: "Apa arti dari kanji '国'?", jawaban: "negara" },
  { pertanyaan: "Apa arti dari kanji '人'?", jawaban: "orang" },
  { pertanyaan: "Apa arti dari kanji '年'?", jawaban: "tahun" },
  { pertanyaan: "Apa arti dari kanji '大'?", jawaban: "besar" },
  { pertanyaan: "Apa arti dari kanji '十'?", jawaban: "sepuluh" },
  { pertanyaan: "Apa arti dari kanji '二'?", jawaban: "dua" },
  { pertanyaan: "Apa arti dari kanji '本'?", jawaban: "buku / asal / Jepang" },
  { pertanyaan: "Apa arti dari kanji '中'?", jawaban: "tengah / dalam" },
  { pertanyaan: "Apa arti dari kanji '長'?", jawaban: "panjang / pemimpin" },
  { pertanyaan: "Apa arti dari kanji '出'?", jawaban: "keluar" },
  { pertanyaan: "Apa arti dari kanji '三'?", jawaban: "tiga" },
  { pertanyaan: "Apa arti dari kanji '時'?", jawaban: "waktu / jam" },
  { pertanyaan: "Apa arti dari kanji '行'?", jawaban: "pergi / melakukan" },
  { pertanyaan: "Apa arti dari kanji '見'?", jawaban: "melihat" },
  { pertanyaan: "Apa arti dari kanji '月'?", jawaban: "bulan" },
  { pertanyaan: "Apa arti dari kanji '分'?", jawaban: "menit / bagian" },
  { pertanyaan: "Apa arti dari kanji '後'?", jawaban: "setelah / belakang" },
  { pertanyaan: "Apa arti dari kanji '前'?", jawaban: "sebelum / depan" },
  { pertanyaan: "Apa arti dari kanji '生'?", jawaban: "hidup / lahir" },
  { pertanyaan: "Apa arti dari kanji '五'?", jawaban: "lima" },
  { pertanyaan: "Apa arti dari kanji '間'?", jawaban: "antara / waktu" },
  { pertanyaan: "Apa arti dari kanji '上'?", jawaban: "atas" },
  { pertanyaan: "Apa arti dari kanji '東'?", jawaban: "timur" },
  { pertanyaan: "Apa arti dari kanji '四'?", jawaban: "empat" },
  { pertanyaan: "Apa arti dari kanji '今'?", jawaban: "sekarang" },
  { pertanyaan: "Apa arti dari kanji '金'?", jawaban: "emas / uang / hari Jumat" },
  { pertanyaan: "Apa arti dari kanji '九'?", jawaban: "sembilan" },
  { pertanyaan: "Apa arti dari kanji '入'?", jawaban: "masuk" },
  { pertanyaan: "Apa arti dari kanji '学'?", jawaban: "belajar" },
  { pertanyaan: "Apa arti dari kanji '高'?", jawaban: "tinggi / mahal" },
  { pertanyaan: "Apa arti dari kanji '円'?", jawaban: "yen / bulat" },
  { pertanyaan: "Apa arti dari kanji '子'?", jawaban: "anak" },
  { pertanyaan: "Apa arti dari kanji '外'?", jawaban: "luar" },
  { pertanyaan: "Apa arti dari kanji '八'?", jawaban: "delapan" },
  { pertanyaan: "Apa arti dari kanji '六'?", jawaban: "enam" },
  { pertanyaan: "Apa arti dari kanji '下'?", jawaban: "bawah" },
  { pertanyaan: "Apa arti dari kanji '来'?", jawaban: "datang" },
  { pertanyaan: "Apa arti dari kanji '気'?", jawaban: "energi / semangat" },
  { pertanyaan: "Apa arti dari kanji '小'?", jawaban: "kecil" },
  { pertanyaan: "Apa arti dari kanji '七'?", jawaban: "tujuh" },
  { pertanyaan: "Apa arti dari kanji '山'?", jawaban: "gunung" },
  { pertanyaan: "Apa arti dari kanji '話'?", jawaban: "bicara / percakapan" },
  { pertanyaan: "Apa arti dari kanji '女'?", jawaban: "perempuan" },
  { pertanyaan: "Apa arti dari kanji '北'?", jawaban: "utara" },
  { pertanyaan: "Apa arti dari kanji '午'?", jawaban: "siang (waktu)" },
  { pertanyaan: "Apa arti dari kanji '百'?", jawaban: "seratus" },
  { pertanyaan: "Apa arti dari kanji '書'?", jawaban: "menulis" },
  { pertanyaan: "Apa arti dari kanji '先'?", jawaban: "sebelum / depan / dahulu" },
  { pertanyaan: "Apa arti dari kanji '名'?", jawaban: "nama" },
  { pertanyaan: "Apa arti dari kanji '川'?", jawaban: "sungai" },
  { pertanyaan: "Apa arti dari kanji '千'?", jawaban: "seribu" },
  { pertanyaan: "Apa arti dari kanji '水'?", jawaban: "air" },
  { pertanyaan: "Apa arti dari kanji '半'?", jawaban: "setengah" },
  { pertanyaan: "Apa arti dari kanji '男'?", jawaban: "laki-laki" },
  { pertanyaan: "Apa arti dari kanji '西'?", jawaban: "barat" },
  { pertanyaan: "Apa arti dari kanji '電'?", jawaban: "listrik" },
  { pertanyaan: "Apa arti dari kanji '校'?", jawaban: "sekolah" },
  { pertanyaan: "Apa arti dari kanji '語'?", jawaban: "bahasa / kata" },
  { pertanyaan: "Apa arti dari kanji '土'?", jawaban: "tanah / bumi" },
  { pertanyaan: "Apa arti dari kanji '木'?", jawaban: "pohon / kayu" },
  { pertanyaan: "Apa arti dari kanji '聞'?", jawaban: "mendengar / bertanya" },
  { pertanyaan: "Apa arti dari kanji '食'?", jawaban: "makan" },
  { pertanyaan: "Apa arti dari kanji '車'?", jawaban: "mobil / kendaraan" },
  { pertanyaan: "Apa arti dari kanji '何'?", jawaban: "apa" }
];

