window.soalKuis = [
  { pertanyaan: "Apa arti dari '学校（がっこう）'?", jawaban: "Sekolah" },
  { pertanyaan: "Apa arti dari '電車（でんしゃ）'?", jawaban: "Kereta listrik" },
  { pertanyaan: "Apa arti dari '水（みず）'?", jawaban: "Air" },
  { pertanyaan: "Apa arti dari '本（ほん）'?", jawaban: "Buku" },
  { pertanyaan: "Apa arti dari '猫（ねこ）'?", jawaban: "Kucing" },
  { pertanyaan: "Apa arti dari '先生（せんせい）'?", jawaban: "Guru" },
  { pertanyaan: "Apa arti dari '病院（びょういん）'?", jawaban: "Rumah sakit" },
  { pertanyaan: "Apa arti dari '傘（かさ）'?", jawaban: "Payung" },
  { pertanyaan: "Apa arti dari '時計（とけい）'?", jawaban: "Jam" },
  { pertanyaan: "Apa arti dari '山（やま）'?", jawaban: "Gunung" },
  { pertanyaan: "Apa arti dari '雨（あめ）'?", jawaban: "Hujan" },
  { pertanyaan: "Apa arti dari '車（くるま）'?", jawaban: "Mobil" },
  { pertanyaan: "Apa arti dari '魚（さかな）'?", jawaban: "Ikan" },
  { pertanyaan: "Apa arti dari '花（はな）'?", jawaban: "Bunga" },
  { pertanyaan: "Apa arti dari '空（そら）'?", jawaban: "Langit" },
  { pertanyaan: "Apa arti dari '友達（ともだち）'?", jawaban: "Teman" },
  { pertanyaan: "Apa arti dari '朝（あさ）'?", jawaban: "Pagi" },
  { pertanyaan: "Apa arti dari '写真（しゃしん）'?", jawaban: "Foto" },
  { pertanyaan: "Apa arti dari '電話（でんわ）'?", jawaban: "Telepon" },
  { pertanyaan: "Apa arti dari '英語（えいご）'?", jawaban: "Bahasa Inggris" },
  { pertanyaan: "Apa arti dari '飛行機（ひこうき）'?", jawaban: "Pesawat" },
  { pertanyaan: "Apa arti dari '帽子（ぼうし）'?", jawaban: "Topi" },
  { pertanyaan: "Apa arti dari '鞄（かばん）'?", jawaban: "Tas" },
  { pertanyaan: "Apa arti dari '家族（かぞく）'?", jawaban: "Keluarga" },
  { pertanyaan: "Apa arti dari 'お金（おかね）'?", jawaban: "Uang" },
  { pertanyaan: "Apa arti dari '飲み物（のみもの）'?", jawaban: "Minuman" },
  { pertanyaan: "Apa arti dari '食べ物（たべもの）'?", jawaban: "Makanan" },
  { pertanyaan: "Apa arti dari '銀行（ぎんこう）'?", jawaban: "Bank" },
  { pertanyaan: "Apa arti dari '公園（こうえん）'?", jawaban: "Taman" },
  { pertanyaan: "Apa arti dari '手紙（てがみ）'?", jawaban: "Surat" },
  { pertanyaan: "Apa arti dari '写真機（しゃしんき）'?", jawaban: "Kamera" },
  { pertanyaan: "Apa arti dari '教室（きょうしつ）'?", jawaban: "Kelas" },
  { pertanyaan: "Apa arti dari '切手（きって）'?", jawaban: "Perangko" },
  { pertanyaan: "Apa arti dari '店（みせ）'?", jawaban: "Toko" },
  { pertanyaan: "Apa arti dari '自転車（じてんしゃ）'?", jawaban: "Sepeda" },
  { pertanyaan: "Apa arti dari '皿（さら）'?", jawaban: "Piring" },
  { pertanyaan: "Apa arti dari '牛乳（ぎゅうにゅう）'?", jawaban: "Susu" },
  { pertanyaan: "Apa arti dari '肉（にく）'?", jawaban: "Daging" },
  { pertanyaan: "Apa arti dari '卵（たまご）'?", jawaban: "Telur" },
  { pertanyaan: "Apa arti dari '海（うみ）'?", jawaban: "Laut" },
  { pertanyaan: "Apa arti dari '家（いえ）'?", jawaban: "Rumah" },
  { pertanyaan: "Apa arti dari '窓（まど）'?", jawaban: "Jendela" },
  { pertanyaan: "Apa arti dari '階段（かいだん）'?", jawaban: "Tangga" },
  { pertanyaan: "Apa arti dari '靴（くつ）'?", jawaban: "Sepatu" },
  { pertanyaan: "Apa arti dari '雑誌（ざっし）'?", jawaban: "Majalah" },
  { pertanyaan: "Apa arti dari '鳥（とり）'?", jawaban: "Burung" },
  { pertanyaan: "Apa arti dari '牛（うし）'?", jawaban: "Sapi" },
  { pertanyaan: "Apa arti dari '道（みち）'?", jawaban: "Jalan" },
  { pertanyaan: "Apa arti dari '畳（たたみ）'?", jawaban: "Tikaran Jepang" },
  { pertanyaan: "Apa arti dari '冷蔵庫（れいぞうこ）'?", jawaban: "Kulkas" },
  { pertanyaan: "Apa arti dari '庭（にわ）'?", jawaban: "Kebun" },
  { pertanyaan: "Apa arti dari '教会（きょうかい）'?", jawaban: "Gereja" },
  { pertanyaan: "Apa arti dari '椅子（いす）'?", jawaban: "Kursi" },
  { pertanyaan: "Apa arti dari '飛行場（ひこうじょう）'?", jawaban: "Bandara" },
  { pertanyaan: "Apa arti dari '運転手（うんてんしゅ）'?", jawaban: "Pengemudi" },
  { pertanyaan: "Apa arti dari '勉強（べんきょう）'?", jawaban: "Belajar" },
  { pertanyaan: "Apa arti dari '音楽（おんがく）'?", jawaban: "Musik" },
  { pertanyaan: "Apa arti dari '漢字（かんじ）'?", jawaban: "Huruf Kanji" },
  { pertanyaan: "Apa arti dari '映画（えいが）'?", jawaban: "Film" },
  { pertanyaan: "Apa arti dari '机（つくえ）'?", jawaban: "Meja" },
  { pertanyaan: "Apa arti dari '空港（くうこう）'?", jawaban: "Bandara" },
  { pertanyaan: "Apa arti dari '財布（さいふ）'?", jawaban: "Dompet" },
  { pertanyaan: "Apa arti dari '電気（でんき）'?", jawaban: "Listrik" },
  { pertanyaan: "Apa arti dari '静か（しずか）'?", jawaban: "Tenang" },
  { pertanyaan: "Apa arti dari '箱（はこ）'?", jawaban: "Kotak" },
  { pertanyaan: "Apa arti dari '泳ぎ（およぎ）'?", jawaban: "Renang" },
  { pertanyaan: "Apa arti dari '台所（だいどころ）'?", jawaban: "Dapur" },
  { pertanyaan: "Apa arti dari '眼鏡（めがね）'?", jawaban: "Kaca mata" },
  { pertanyaan: "Apa arti dari '橋（はし）'?", jawaban: "Jembatan" },
  { pertanyaan: "Apa arti dari '鉛筆（えんぴつ）'?", jawaban: "Pensil" },
  { pertanyaan: "Apa arti dari '夏（なつ）'?", jawaban: "Musim panas" },
  { pertanyaan: "Apa arti dari '地図（ちず）'?", jawaban: "Peta" },
  { pertanyaan: "Apa arti dari '晩ご飯（ばんごはん）'?", jawaban: "Makan malam" },
  { pertanyaan: "Apa arti dari '誕生日（たんじょうび）'?", jawaban: "Ulang tahun" },
  { pertanyaan: "Apa arti dari '音（おと）'?", jawaban: "Bunyi" },
  { pertanyaan: "Apa arti dari '町（まち）'?", jawaban: "Kota" },
  { pertanyaan: "Apa arti dari '紙（かみ）'?", jawaban: "Kertas" },
  { pertanyaan: "Apa arti dari '郵便局（ゆうびんきょく）'?", jawaban: "Kantor pos" },
  { pertanyaan: "Apa arti dari '鉄道（てつどう）'?", jawaban: "Jalur kereta" },
  { pertanyaan: "Apa arti dari '昼ご飯（ひるごはん）'?", jawaban: "Makan siang" },
  { pertanyaan: "Apa arti dari '声（こえ）'?", jawaban: "Suara" },
  { pertanyaan: "Apa arti dari '旅行（りょこう）'?", jawaban: "Wisata" },
  { pertanyaan: "Apa arti dari '話（はなし）'?", jawaban: "Cerita" },
  { pertanyaan: "Apa arti dari '電話番号（でんわばんごう）'?", jawaban: "Nomor telepon" },
  { pertanyaan: "Apa arti dari '食事（しょくじ）'?", jawaban: "Waktu makan" },
  { pertanyaan: "Apa arti dari '夕方（ゆうがた）'?", jawaban: "Sore" },
  { pertanyaan: "Apa arti dari '部屋（へや）'?", jawaban: "Kamar" },
  { pertanyaan: "Apa arti dari '食堂（しょくどう）'?", jawaban: "Kantin" }
];
