window.soalKuis = [
  { pertanyaan: "Apa furigana dari kanji '日'?", jawaban: "にち / ひ" },
  { pertanyaan: "Apa furigana dari kanji '一'?", jawaban: "いち" },
  { pertanyaan: "Apa furigana dari kanji '国'?", jawaban: "くに" },
  { pertanyaan: "Apa furigana dari kanji '人'?", jawaban: "ひと / じん / にん" },
  { pertanyaan: "Apa furigana dari kanji '年'?", jawaban: "とし" },
  { pertanyaan: "Apa furigana dari kanji '大'?", jawaban: "だい / おお" },
  { pertanyaan: "Apa furigana dari kanji '十'?", jawaban: "じゅう" },
  { pertanyaan: "Apa furigana dari kanji '二'?", jawaban: "に" },
  { pertanyaan: "Apa furigana dari kanji '本'?", jawaban: "ほん" },
  { pertanyaan: "Apa furigana dari kanji '中'?", jawaban: "ちゅう / なか" },
  { pertanyaan: "Apa furigana dari kanji '長'?", jawaban: "なが / ちょう" },
  { pertanyaan: "Apa furigana dari kanji '出'?", jawaban: "で / しゅつ" },
  { pertanyaan: "Apa furigana dari kanji '三'?", jawaban: "さん / みっ" },
  { pertanyaan: "Apa furigana dari kanji '時'?", jawaban: "じ / とき" },
  { pertanyaan: "Apa furigana dari kanji '行'?", jawaban: "い / こう" },
  { pertanyaan: "Apa furigana dari kanji '見'?", jawaban: "み / けん" },
  { pertanyaan: "Apa furigana dari kanji '月'?", jawaban: "つき / げつ / がつ" },
  { pertanyaan: "Apa furigana dari kanji '分'?", jawaban: "ふん / ぶん / わ" },
  { pertanyaan: "Apa furigana dari kanji '後'?", jawaban: "ご / あと / うし" },
  { pertanyaan: "Apa furigana dari kanji '前'?", jawaban: "まえ / ぜん" },
  { pertanyaan: "Apa furigana dari kanji '生'?", jawaban: "せい / しょう / い / う / なま" },
  { pertanyaan: "Apa furigana dari kanji '五'?", jawaban: "ご / いつ" },
  { pertanyaan: "Apa furigana dari kanji '間'?", jawaban: "あいだ / かん / ま" },
  { pertanyaan: "Apa furigana dari kanji '上'?", jawaban: "うえ / じょう / あ / のぼ" },
  { pertanyaan: "Apa furigana dari kanji '東'?", jawaban: "ひがし / とう" },
  { pertanyaan: "Apa furigana dari kanji '四'?", jawaban: "し / よん / よ" },
  { pertanyaan: "Apa furigana dari kanji '今'?", jawaban: "いま / こん" },
  { pertanyaan: "Apa furigana dari kanji '金'?", jawaban: "きん / かね / かな" },
  { pertanyaan: "Apa furigana dari kanji '九'?", jawaban: "きゅう / く" },
  { pertanyaan: "Apa furigana dari kanji '入'?", jawaban: "い / はい / にゅう" },
  { pertanyaan: "Apa furigana dari kanji '学'?", jawaban: "がく / まな" },
  { pertanyaan: "Apa furigana dari kanji '高'?", jawaban: "たか / こう" },
  { pertanyaan: "Apa furigana dari kanji '円'?", jawaban: "えん" },
  { pertanyaan: "Apa furigana dari kanji '子'?", jawaban: "こ / し" },
  { pertanyaan: "Apa furigana dari kanji '外'?", jawaban: "そと / がい" },
  { pertanyaan: "Apa furigana dari kanji '八'?", jawaban: "はち / やっ" },
  { pertanyaan: "Apa furigana dari kanji '六'?", jawaban: "ろく / むっ" },
  { pertanyaan: "Apa furigana dari kanji '下'?", jawaban: "した / しも / さ / くだ / か" },
  { pertanyaan: "Apa furigana dari kanji '来'?", jawaban: "く / き / らい" },
  { pertanyaan: "Apa furigana dari kanji '気'?", jawaban: "き" },
  { pertanyaan: "Apa furigana dari kanji '小'?", jawaban: "ちい / しょう" },
  { pertanyaan: "Apa furigana dari kanji '七'?", jawaban: "しち / なな" },
  { pertanyaan: "Apa furigana dari kanji '山'?", jawaban: "やま / さん" },
  { pertanyaan: "Apa furigana dari kanji '話'?", jawaban: "はな / わ" },
  { pertanyaan: "Apa furigana dari kanji '女'?", jawaban: "おんな / じょ" },
  { pertanyaan: "Apa furigana dari kanji '北'?", jawaban: "きた / ほく" },
  { pertanyaan: "Apa furigana dari kanji '午'?", jawaban: "ご" },
  { pertanyaan: "Apa furigana dari kanji '百'?", jawaban: "ひゃく" },
  { pertanyaan: "Apa furigana dari kanji '書'?", jawaban: "か / しょ" },
  { pertanyaan: "Apa furigana dari kanji '先'?", jawaban: "さき / せん" },
  { pertanyaan: "Apa furigana dari kanji '名'?", jawaban: "な / めい" },
  { pertanyaan: "Apa furigana dari kanji '川'?", jawaban: "かわ / がわ" },
  { pertanyaan: "Apa furigana dari kanji '千'?", jawaban: "せん / ち" },
  { pertanyaan: "Apa furigana dari kanji '水'?", jawaban: "みず / すい" },
  { pertanyaan: "Apa furigana dari kanji '半'?", jawaban: "はん" },
  { pertanyaan: "Apa furigana dari kanji '男'?", jawaban: "おとこ / だん" },
  { pertanyaan: "Apa furigana dari kanji '西'?", jawaban: "にし / せい / さい" },
  { pertanyaan: "Apa furigana dari kanji '電'?", jawaban: "でん" },
  { pertanyaan: "Apa furigana dari kanji '校'?", jawaban: "こう" },
  { pertanyaan: "Apa furigana dari kanji '語'?", jawaban: "ご / かた" },
  { pertanyaan: "Apa furigana dari kanji '土'?", jawaban: "つち / ど" },
  { pertanyaan: "Apa furigana dari kanji '木'?", jawaban: "き / もく" },
  { pertanyaan: "Apa furigana dari kanji '聞'?", jawaban: "き / ぶん" },
  { pertanyaan: "Apa furigana dari kanji '食'?", jawaban: "た / しょく" },
  { pertanyaan: "Apa furigana dari kanji '車'?", jawaban: "くるま / しゃ" },
  { pertanyaan: "Apa furigana dari kanji '何'?", jawaban: "なに / なん" },
  { pertanyaan: "Apa furigana dari kanji '南'?", jawaban: "みなみ" },
  { pertanyaan: "Apa furigana dari kanji '万'?", jawaban: "まん" },
  { pertanyaan: "Apa furigana dari kanji '毎'?", jawaban: "まい" },
  { pertanyaan: "Apa furigana dari kanji '白'?", jawaban: "しろ" },
  { pertanyaan: "Apa furigana dari kanji '天'?", jawaban: "てん" },
  { pertanyaan: "Apa furigana dari kanji '母'?", jawaban: "はは" },
  { pertanyaan: "Apa furigana dari kanji '火'?", jawaban: "ひ / び / か" },
  { pertanyaan: "Apa furigana dari kanji '右'?", jawaban: "みぎ" },
  { pertanyaan: "Apa furigana dari kanji '読'?", jawaban: "よむ / よみ / どく / とう" },
  { pertanyaan: "Apa furigana dari kanji '友'?", jawaban: "とも" },
  { pertanyaan: "Apa furigana dari kanji '左'?", jawaban: "ひだり" },
  { pertanyaan: "Apa furigana dari kanji '休'?", jawaban: "やす" },
  { pertanyaan: "Apa furigana dari kanji '父'?", jawaban: "ちち" },
  { pertanyaan: "Apa furigana dari kanji '雨'?", jawaban: "あめ" }
];
