window.soalKuis = [
  { pertanyaan: "Apa arti dari 'おおきい'?", jawaban: "Besar" },
  { pertanyaan: "Apa arti dari 'あつい'?", jawaban: "Panas" },
  { pertanyaan: "Apa arti dari 'さむい'?", jawaban: "Dingin (cuaca)" },
  { pertanyaan: "Apa arti dari 'みじかい'?", jawaban: "Pendek" },
  { pertanyaan: "Apa arti dari 'やすい'?", jawaban: "Murah" },
  { pertanyaan: "Apa arti dari 'おいしい'?", jawaban: "Enak" },
  { pertanyaan: "Apa arti dari 'たかい'?", jawaban: "Tinggi" },
  { pertanyaan: "Apa arti dari 'あかい'?", jawaban: "Merah" },
  { pertanyaan: "Apa arti dari 'わるい'?", jawaban: "Buruk" },
  { pertanyaan: "Apa arti dari 'ながい'?", jawaban: "Panjang" },
  { pertanyaan: "Apa arti dari 'たのしい'?", jawaban: "Menyenangkan" },
  { pertanyaan: "Apa arti dari 'うるさい'?", jawaban: "Berisik" },
  { pertanyaan: "Apa arti dari 'あかるい'?", jawaban: "Terang" },
  { pertanyaan: "Apa arti dari 'すずしい'?", jawaban: "Dingin (angin)" },
  { pertanyaan: "Apa arti dari 'おもい'?", jawaban: "Berat" },
  { pertanyaan: "Apa arti dari 'わかい'?", jawaban: "Muda" },
  { pertanyaan: "Apa arti dari 'ふるい'?", jawaban: "Tua" },
  { pertanyaan: "Apa arti dari 'あたらしい'?", jawaban: "Baru" },
  { pertanyaan: "Apa arti dari 'うれしい'?", jawaban: "Menyenangkan" },
  { pertanyaan: "Apa arti dari 'かなしい'?", jawaban: "Sedih" },
  { pertanyaan: "Apa arti dari 'やさしい'?", jawaban: "Baik" },
  { pertanyaan: "Apa arti dari 'いそがしい'?", jawaban: "Sibuk" },
  { pertanyaan: "Apa arti dari 'すごい'?", jawaban: "Luar biasa" },
  { pertanyaan: "Apa arti dari 'きれい'?", jawaban: "Bersih" },
  { pertanyaan: "Apa arti dari 'きたない'?", jawaban: "Kotor" },
  { pertanyaan: "Apa arti dari 'せまい'?", jawaban: "Sempit" },
  { pertanyaan: "Apa arti dari 'ひろい'?", jawaban: "Luas" },
  { pertanyaan: "Apa arti dari 'あたたかい'?", jawaban: "Hangat" },
  { pertanyaan: "Apa arti dari 'かるい'?", jawaban: "Ringan" },
  { pertanyaan: "Apa arti dari 'ふとい'?", jawaban: "Gemuk" },
  { pertanyaan: "Apa arti dari 'おそい'?", jawaban: "Lambat" }
];
